# Extracting Information From RAD/PACT Guides

The following code extracts housing data found in a PDF and formats it into tabular data. The [PDF](https://www.nyc.gov/assets/nycha/downloads/pdf/radpact-guide.pdf) is the New York City Housing Authority's latest list of converted PACT developments, made available in July 2025.

In [1]:
## import libraries
import pandas as pd
import numpy as np
import pdfplumber
import re
import csv

In [2]:
## read in the pdf
pdf = pdfplumber.open('../input/radpact-guide-07-2025.pdf')

In [3]:
## create empty lists for later
developments = []
extra_developments = []

In [4]:
## loop through pages and extract data
for page_num, page in enumerate(pdf.pages): # <-- for each page in the document...

    tables = page.extract_tables() # <-- exract every table
    print(f"page {page_num}: found {len(tables)} tables")

    for table in tables: # <-- then, for each table found...
        
        if table and re.match(r'^BBL$',table[0][0]): # <-- if it's a table and the first item in the first row in that table is BBL...
            headers = table[0] # <-- then first row is headers
            data = table[1:] # <-- remaining rows are data
            df = pd.DataFrame(columns=headers, data=data) # <-- transform into dataframe
            developments.append(df) # <-- append each dataframe (table) to an empty list
        else: # otherwise...
            extra_headers = ['BBL', 'BLDG#', 'M', 'ADDRESS', 'ZIP CODE', 'CD #', 'FC #', 'SS #', 'SA #', 'CC #', 'BIN#']
            extra = table
            dfs = pd.DataFrame(columns=headers, data=extra)
            extra_developments.append(dfs)

page 0: found 6 tables
page 1: found 2 tables
page 2: found 4 tables
page 3: found 2 tables
page 4: found 6 tables
page 5: found 5 tables
page 6: found 6 tables
page 7: found 2 tables
page 8: found 3 tables
page 9: found 3 tables
page 10: found 5 tables
page 11: found 2 tables
page 12: found 2 tables
page 13: found 6 tables
page 14: found 4 tables
page 15: found 4 tables
page 16: found 4 tables
page 17: found 2 tables
page 18: found 1 tables
page 19: found 1 tables
page 20: found 1 tables
page 21: found 3 tables
page 22: found 5 tables
page 23: found 5 tables
page 24: found 5 tables
page 25: found 5 tables
page 26: found 3 tables
page 27: found 5 tables
page 28: found 4 tables
page 29: found 4 tables
page 30: found 4 tables
page 31: found 6 tables
page 32: found 4 tables
page 33: found 2 tables
page 34: found 1 tables
page 35: found 1 tables
page 36: found 2 tables

In [5]:
## concat the dfs together into singular dfs
extras_combined = pd.concat(extra_developments, ignore_index=True)
combined_df = pd.concat(developments, ignore_index=True)

In [6]:
## now combine the two larger dfs into one
all_combined = pd.concat([extras_combined,combined_df], ignore_index=True)

In [7]:
## check number of addresses
all_combined.ADDRESS.nunique()

1538

In [8]:
all_combined.ADDRESS.unique().tolist()

['346 CLIFTON PLACE',
 '344 CLIFTON PLACE',
 '360 NOSTRAND AVENUE',
 '260 LEXINGTON AVENUE',
 '262 LEXINGTON AVENUE',
 '264 LEXINGTON AVENUE',
 '254 LEXINGTON AVENUE',
 '252 LEXINGTON AVENUE',
 '252A LEXINGTON AVENUE',
 '250 LEXINGTON AVENUE',
 '366 CLIFTON PLACE',
 '380 CLIFTON PLACE',
 '388 CLIFTON PLACE',
 '396 CLIFTON PLACE',
 '545 GREENE AVENUE',
 '555 GREENE AVENUE',
 '304 LEXINGTON AVENUE',
 '302 LEXINGTON AVENUE',
 '300 LEXINGTON AVENUE',
 '298 LEXINGTON AVENUE',
 '296 LEXINGTON AVENUE',
 '294 LEXINGTON AVENUE',
 '292 LEXINGTON AVENUE',
 '290 LEXINGTON AVENUE',
 '288 LEXINGTON AVENUE',
 '286 LEXINGTON AVENUE',
 '284 LEXINGTON AVENUE',
 '282 LEXINGTON AVENUE',
 '280 LEXINGTON AVENUE',
 '278 LEXINGTON AVENUE',
 '310 LEXINGTON AVENUE',
 '320 LEXINGTON AVENUE',
 '330 LEXINGTON AVENUE',
 '336 LEXINGTON AVENUE',
 '435 GATES AVENUE',
 '441 GATES AVENUE',
 '447 GATES AVENUE',
 '449 GATES AVENUE',
 '451 GATES AVENUE',
 '453 GATES AVENUE',
 '455 GATES AVENUE',
 '457 GATES AVENUE',
 '459 GATES AVENUE',
 '461 GATES AVENUE',
 '463 GATES AVENUE',
 '465 GATES AVENUE',
 '467 GATES AVENUE',
 '469 GATES AVENUE',
 '471 GATES AVENUE',
 '473 GATES AVENUE',
 '475 GATES AVENUE',
 '375 LEXINGTON AVENUE',
 '385 LEXINGTON AVENUE',
 '395 LEXINGTON AVENUE',
 '405 LEXINGTON AVENUE',
 '415 LEXINGTON AVENUE',
 '280 TOMPKINS AVENUE',
 '360 LEXINGTON AVENUE',
 '370 LEXINGTON AVENUE',
 '380 LEXINGTON AVENUE',
 '390 LEXINGTON AVENUE',
 '775 MARCY AVENUE',
 '785 MARCY AVENUE',
 '791 MARCY AVENUE',
 '499 GATES AVENUE',
 '505 GATES AVENUE',
 '515 GATES AVENUE',
 '495 GATES AVENUE',
 '96 SOUTH 10TH STREET',
 '699 EAST 139TH STREET',
 '409 EAST 146TH STREET',
 '411 EAST 146TH STREET',
 '413 EAST 146TH STREET',
 '415 EAST 146TH STREET',
 '445 EAST 146TH STREET',
 '785 SCHENCK AVENUE',
 '2150 LINDEN BOULEVARD',
 '797 SCHENCK AVENUE',
 '842 ASHFORD STREET',
 '773 STANLEY AVENUE',
 '854 ASHFORD STREET',
 '845 SCHENCK AVENUE',
 '857 SCHENCK AVENUE',
 '881 SCHENCK AVENUE',
 '893 SCHENCK AVENUE',
 '726 STANLEY AVENUE',
 '738 STANLEY AVENUE',
 '740 STANLEY AVENUE',
 '359 WORTMAN AVENUE',
 '357 WORTMAN AVENUE',
 '756 STANLEY AVENUE',
 '758 STANLEY AVENUE',
 '772 STANLEY AVENUE',
 '363 WORTMAN AVENUE',
 '361 WORTMAN AVENUE',
 '872 ASHFORD STREET',
 '884 ASHFORD STREET',
 '908 ASHFORD STREET',
 '920 ASHFORD STREET',
 '817 SCHENCK AVENUE',
 '829 SCHENCK AVENUE',
 '2156 LINDEN BOULEVARD',
 '807 SCHENCK AVENUE',
 '725 STANLEY AVENUE',
 '2202 LINDEN BOULEVARD',
 '830 ASHFORD STREET',
 '765 STANLEY AVENUE',
 '812 ASHFORD STREET',
 '828 ASHFORD STREET',
 '804 ASHFORD STREET',
 '816 ASHFORD STREET',
 '1280 GREENE AVENUE',
 '1240 GREENE AVENUE',
 '289 CENTRAL AVENUE',
 '595 EVERGREEN AVENUE',
 '615 EVERGREEN AVENUE',
 '690 EVERGREEN AVENUE',
 '670 EVERGREEN AVENUE',
 '85 COVERT STREET',
 '75 COVERT STREET',
 '160 HIMROD STREET',
 '234 GROVE STREET',
 '230 GROVE STREET',
 '226 GROVE STREET',
 '339 WILSON AVENUE',
 '343 WILSON AVENUE',
 '347 WILSON AVENUE',
 '235 LINDEN STREET',
 '239 LINDEN STREET',
 '243 LINDEN STREET',
 '247 LINDEN STREET',
 '251 LINDEN STREET',
 '532 KNICKERBOCKER AVENUE',
 '528 KNICKERBOCKER AVENUE',
 '524 KNICKERBOCKER AVENUE',
 '236 LINDEN STREET',
 '232 LINDEN STREET',
 '228 LINDEN STREET',
 '224 LINDEN STREET',
 '220 LINDEN STREET',
 '357 WILSON AVENUE',
 '361 WILSON AVENUE',
 '365 WILSON AVENUE',
 '1389 GATES AVENUE',
 '1393 GATES AVENUE',
 '1397 GATES AVENUE',
 '1411 GATES AVENUE',
 '1415 GATES AVENUE',
 '558 KNICKERBOCKER AVENUE',
 '554 KNICKERBOCKER AVENUE',
 '550 KNICKERBOCKER AVENUE',
 '1371 SAINT MARKS AVENUE',
 '1629 PARK PLACE',
 '1630 PARK PLACE',
 '1636 PARK PLACE',
 '1640 PARK PLACE',
 '1646 PARK PLACE',
 '1240 BURKE AVENUE',
 '1246 BURKE AVENUE',
 '1260 BURKE AVENUE',
 '3055 BOUCK AVENUE',
 '1255 ADEE AVENUE',
 '1245 ADEE AVENUE',
 '1221 ADEE AVENUE',
 '1219 ADEE AVENUE',
 '1160 229TH DRIVE SOUTH',
 '1187 226TH DRIVE',
 '1183 226TH DRIVE',
 '1169 226TH DRIVE',
 '1165 226TH DRIVE',
 '1151 226TH DRIVE',
 '1145 226TH DRIVE',
 '1141 226TH DRIVE',
 '1131 226TH DRIVE',
 '1135 226TH DRIVE',
 '4000 LACONIA AVENUE',
 '4010 LACONIA AVENUE',
 '1115 EAST 225TH STREET',
 '1121 EAST 225TH STREET',
 '1138 226TH DRIVE',
 '1130 226TH DRIVE',
 '1155 EAST 225TH STREET',
 '1161 EAST 225TH STREET',
 '1181 EAST 225TH STREET',
 '1175 EAST 225TH STREET',
 '3841 BAYCHESTER AVENUE',
 '3845 BAYCHESTER AVENUE',
 '1195 EAST 225TH STREET',
 '1855 SCHIEFFELIN AVENUE',
 '1140 EAST 229TH STREET',
 '1150 EAST 229TH STREET',
 '1149GAR 229TH DRIVE NORTH',
 '1981 SCHIEFFELIN AVENUE',
 '1985 SCHIEFFELIN AVENUE',
 '1961 SCHIEFFELIN AVENUE',
 '1965 SCHIEFFELIN AVENUE',
 '1173 229TH DRIVE NORTH',
 '1161 229TH DRIVE NORTH',
 '1159 229TH DRIVE NORTH',
 '1147 229TH DRIVE NORTH',
 '1149 229TH DRIVE NORTH',
 '738 FENIMORE STREET',
 '736 FENIMORE STREET',
 '732 FENIMORE STREET',
 '1390 FRANKLIN AVENUE',
 '58 MACOMBS PLACE',
 '56 1/2 MACOMBS PLACE',
 '54 1/2 MACOMBS PLACE',
 '52 MACOMBS PLACE',
 '56 MACOMBS PLACE',
 '50 MACOMBS PLACE',
 '48 MACOMBS PLACE',
 '46 MACOMBS PLACE',
 '40 1/2 MACOMBS PLACE',
 '42 MACOMBS PLACE',
 '42 1/2 MACOMBS PLACE',
 '44 MACOMBS PLACE',
 '2653 A C POWELL BOULEVARD',
 '2651 A C POWELL BOULEVARD',
 '2645 A C POWELL BOULEVARD',
 '2641 A C POWELL BOULEVARD',
 '187 WEST 152ND STREET',
 '183 WEST 152ND STREET',
 '180 WEST 152ND STREET',
 '182 WEST 152ND STREET',
 '186 WEST 152ND STREET',
 '2637 A C POWELL BOULEVARD',
 '190 WEST 152ND STREET',
 '2627 A C POWELL BOULEVARD',
 '191W WEST 151ST STREET',
 '2633 A C POWELL BOULEVARD',
 '2621 A C POWELL BOULEVARD',
 '191V WEST 151ST STREET',
 '191U WEST 151ST STREET',
 '181 WEST 151ST STREET',
 '177 WEST 151ST STREET',
 '173 WEST 151ST STREET',
 '578 HOWARD AVENUE',
 '582 HOWARD AVENUE',
 '602 HOWARD AVENUE',
 '606 HOWARD AVENUE',
 '610 HOWARD AVENUE',
 '614 HOWARD AVENUE',
 '1 TAPSCOTT STREET',
 '5 TAPSCOTT STREET',
 '9 TAPSCOTT STREET',
 '13 TAPSCOTT STREET',
 '17 TAPSCOTT STREET',
 '48REAR GRAFTON STREET',
 '1764 STERLING PLACE',
 '1766A STERLING PLACE',
 '1766B STERLING PLACE',
 '1768 STERLING PLACE',
 '1768A STERLING PLACE',
 '1768B STERLING PLACE',
 '1770 STERLING PLACE',
 '1770A STERLING PLACE',
 '1770B STERLING PLACE',
 '1772 STERLING PLACE',
 '1772A STERLING PLACE',
 '1772B STERLING PLACE',
 '1774 STERLING PLACE',
 '1774A STERLING PLACE',
 '498 HOWARD AVENUE',
 '1774B STERLING PLACE',
 '1776 STERLING PLACE',
 '504 HOWARD AVENUE',
 '504A HOWARD AVENUE',
 '504B HOWARD AVENUE',
 '506 HOWARD AVENUE',
 '506A HOWARD AVENUE',
 '506B HOWARD AVENUE',
 '508 HOWARD AVENUE',
 '508A HOWARD AVENUE',
 '510 HOWARD AVENUE',
 '508B HOWARD AVENUE',
 '1679 SAINT JOHNS PLACE',
 '1679A SAINT JOHNS PLACE',
 '1679B SAINT JOHNS PLACE',
 '1681 SAINT JOHNS PLACE',
 '1681A SAINT JOHNS PLACE',
 '1681B SAINT JOHNS PLACE',
 '1683 SAINT JOHNS PLACE',
 '1683A SAINT JOHNS PLACE',
 '1683B SAINT JOHNS PLACE',
 '1685 SAINT JOHNS PLACE',
 '1685A SAINT JOHNS PLACE',
 '1685B SAINT JOHNS PLACE',
 '1687 SAINT JOHNS PLACE',
 '1687A SAINT JOHNS PLACE',
 '1687B SAINT JOHNS PLACE',
 '1689 SAINT JOHNS PLACE',
 '1689A SAINT JOHNS PLACE',
 '1689B SAINT JOHNS PLACE',
 '1691 SAINT JOHNS PLACE',
 '1691A SAINT JOHNS PLACE',
 '1691B SAINT JOHNS PLACE',
 '1693 SAINT JOHNS PLACE',
 '1693A SAINT JOHNS PLACE',
 '1693B SAINT JOHNS PLACE',
 '537 RALPH AVENUE',
 '537A RALPH AVENUE',
 '537B RALPH AVENUE',
 '539 RALPH AVENUE',
 '539A RALPH AVENUE',
 '539B RALPH AVENUE',
 '1702 STERLING PLACE',
 '1716 STERLING PLACE',
 '541 RALPH AVENUE',
 '541A RALPH AVENUE',
 '541B RALPH AVENUE',
 '543 RALPH AVENUE',
 '543A RALPH AVENUE',
 '543B RALPH AVENUE',
 '545 RALPH AVENUE',
 '545A RALPH AVENUE',
 '545B RALPH AVENUE',
 '547 RALPH AVENUE',
 '547A RALPH AVENUE',
 '547B RALPH AVENUE',
 '549 RALPH AVENUE',
 '549A RALPH AVENUE',
 '549B RALPH AVENUE',
 '551 RALPH AVENUE',
 '551A RALPH AVENUE',
 '553 RALPH AVENUE',
 '551B RALPH AVENUE',
 '555 RALPH AVENUE',
 '1651 SAINT JOHNS PLACE',
 '1659 SAINT JOHNS PLACE',
 '1649 SAINT JOHNS PLACE',
 '1720 STERLING PLACE',
 '1720A STERLING PLACE',
 '1720B STERLING PLACE',
 '1722 STERLING PLACE',
 '1722A STERLING PLACE',
 '1722B STERLING PLACE',
 '1724 STERLING PLACE',
 '1724A STERLING PLACE',
 '1724B STERLING PLACE',
 '1726 STERLING PLACE',
 '1726A STERLING PLACE',
 '1726B STERLING PLACE',
 '1728 STERLING PLACE',
 '1728A STERLING PLACE',
 '1728B STERLING PLACE',
 '1730 STERLING PLACE',
 '1730A STERLING PLACE',
 '1730B STERLING PLACE',
 '1732 STERLING PLACE',
 '1732A STERLING PLACE',
 '1732B STERLING PLACE',
 '1734 STERLING PLACE',
 '1734A STERLING PLACE',
 '1734B STERLING PLACE',
 '1736 STERLING PLACE',
 '1736A STERLING PLACE',
 '1736B STERLING PLACE',
 '497 HOWARD AVENUE',
 '497A HOWARD AVENUE',
 '497B HOWARD AVENUE',
 '499 HOWARD AVENUE',
 '499A HOWARD AVENUE',
 '499B HOWARD AVENUE',
 '501 HOWARD AVENUE',
 '501A HOWARD AVENUE',
 '501B HOWARD AVENUE',
 '503 HOWARD AVENUE',
 '503A HOWARD AVENUE',
 '503B HOWARD AVENUE',
 '505 HOWARD AVENUE',
 '505A HOWARD AVENUE',
 '505B HOWARD AVENUE',
 '507 HOWARD AVENUE',
 '507A HOWARD AVENUE',
 '507B HOWARD AVENUE',
 '509 HOWARD AVENUE',
 '509A HOWARD AVENUE',
 '509B HOWARD AVENUE',
 '511 HOWARD AVENUE',
 '511A HOWARD AVENUE',
 '513 HOWARD AVENUE',
 '515 HOWARD AVENUE',
 '1745 SAINT JOHNS PLACE',
 '1737 SAINT JOHNS PLACE',
 '511B HOWARD AVENUE',
 '1790 STERLING PLACE',
 '1790A STERLING PLACE',
 '1790B STERLING PLACE',
 '1792 STERLING PLACE',
 '1792A STERLING PLACE',
 '1792B STERLING PLACE',
 '1794 STERLING PLACE',
 '1794A STERLING PLACE',
 '1794B STERLING PLACE',
 '1796 STERLING PLACE',
 '1796A STERLING PLACE',
 '1796B STERLING PLACE',
 '1798 STERLING PLACE',
 '1798A STERLING PLACE',
 '1798B STERLING PLACE',
 '1800 STERLING PLACE',
 '1800A STERLING PLACE',
 '1800B STERLING PLACE',
 '1802 STERLING PLACE',
 '1802A STERLING PLACE',
 '1802B STERLING PLACE',
 '1804 STERLING PLACE',
 '1804A STERLING PLACE',
 '1804B STERLING PLACE',
 '1810 STERLING PLACE',
 '1814 STERLING PLACE',
 '1812 STERLING PLACE',
 '1806 STERLING PLACE',
 '914 VAN SICLEN AVENUE',
 '225 WORTMAN AVENUE',
 '215 WORTMAN AVENUE',
 '185 WORTMAN AVENUE',
 '187 WORTMAN AVENUE',
 '183 WORTMAN AVENUE',
 '180 WORTMAN AVENUE',
 '54-30 BEACH CHANNEL DRIVE',
 '56-10 BEACH CHANNEL DRIVE',
 '56-16 BEACH CHANNEL DRIVE',
 '54-75 ALMEDA AVENUE',
 '414 BEACH 58TH STREET',
 '57-10 BEACH CHANNEL DRIVE',
 '441 BEACH 51ST STREET',
 '445 BEACH 51ST STREET',
 '434 BEACH 54TH STREET',
 '440 BEACH 54TH STREET',
 '430 BEACH 54TH STREET',
 '444 BEACH 54TH STREET',
 '439 BEACH 54TH STREET',
 '447 BEACH 54TH STREET',
 '443 BEACH 54TH STREET',
 '434 BEACH 58TH STREET',
 '440 BEACH 58TH STREET',
 '54-49 ALMEDA AVENUE',
 '54-41 ALMEDA AVENUE',
 '54-15 ALMEDA AVENUE',
 '54-09 ALMEDA AVENUE',
 '51-49 ALMEDA AVENUE',
 '51-45 ALMEDA AVENUE',
 '51-15 ALMEDA AVENUE',
 '1474 PARK PLACE',
 '1484 PARK PLACE',
 '1480 PARK PLACE',
 '208 ROCHESTER AVENUE',
 '218 ROCHESTER AVENUE',
 '1521 STERLING PLACE',
 '1522 STERLING PLACE',
 '230 ROCHESTER AVENUE',
 '232 ROCHESTER AVENUE',
 '234 ROCHESTER AVENUE',
 '117 WEST 144TH STREET',
 '143 WEST 142ND STREET',
 '145 WEST 142ND STREET',
 '149 WEST 142ND STREET',
 '2453 A C POWELL BOULEVARD',
 '2449 A C POWELL BOULEVARD',
 '2441 A C POWELL BOULEVARD',
 '144 WEST 141ST STREET',
 '2409 A C POWELL BOULEVARD',
 '2407 A C POWELL BOULEVARD',
 '125 WEST 144TH STREET',
 '116 WEST 139TH STREET',
 '112 WEST 139TH STREET',
 '669 LENOX AVENUE',
 '103 WEST 143RD STREET',
 '105 WEST 143RD STREET',
 '129 WEST 144TH STREET',
 '133 WEST 144TH STREET',
 '148 WEST 144TH STREET',
 '158 WEST 144TH STREET',
 '162 WEST 144TH STREET',
 '825 CAULDWELL AVENUE',
 '829 CAULDWELL AVENUE',
 '611 EAST 158TH STREET',
 '615 EAST 158TH STREET',
 '625 EAST 158TH STREET',
 '635 EAST 158TH STREET',
 '645 EAST 158TH STREET',
 '854 EAGLE AVENUE',
 '850 EAGLE AVENUE',
 '844 EAGLE AVENUE',
 '840 EAGLE AVENUE',
 '834 EAGLE AVENUE',
 '830 EAGLE AVENUE',
 '360 FORD STREET',
 '365 FORD STREET, WING A',
 '365 FORD STREET, WING B',
 '353 FORD STREET',
 '355 FORD STREET',
 '365 FORD STREET, WING C',
 '365 FORD STREET',
 '365 EAST 183RD STREET, WING D',
 '365 EAST 183RD STREET, WING E',
 '355 EAST 183RD STREET',
 '365 EAST 183RD STREET, WING F',
 '1575 DEAN STREET',
 '87 TROY AVENUE',
 '1620 PACIFIC STREET',
 '1630 PACIFIC STREET',
 '1640 PACIFIC STREET',
 '1642 PACIFIC STREET',
 '1650 PACIFIC STREET',
 '1660 PACIFIC STREET',
 '1670 PACIFIC STREET',
 '1672 PACIFIC STREET',
 '80 SCHENECTADY AVENUE',
 '188 MARCY AVENUE',
 '190 MARCY AVENUE',
 '227 DIVISION AVENUE',
 '221 DIVISION AVENUE',
 '225 DIVISION AVENUE',
 '223 DIVISION AVENUE',
 '171 SCHOLES STREET',
 '181 SCHOLES STREET',
 '182 STAGG WALK',
 '180 STAGG WALK',
 '178 STAGG WALK',
 '186 STAGG WALK',
 '184 STAGG WALK',
 '183 SCHOLES STREET',
 '185 SCHOLES STREET',
 '197 TEN EYCK WALK',
 '199 TEN EYCK WALK',
 '198 MAUJER STREET',
 '196 MAUJER STREET',
 '200 MAUJER STREET',
 '201 TEN EYCK WALK',
 '203 TEN EYCK WALK',
 '205 TEN EYCK WALK',
 '219 TEN EYCK WALK',
 '216 MAUJER STREET',
 '214 MAUJER STREET',
 '220 MAUJER STREET',
 '138 BUSHWICK AVENUE',
 '136 BUSHWICK AVENUE',
 '218 MAUJER STREET',
 '134 BUSHWICK AVENUE',
 '132 BUSHWICK AVENUE',
 '130 BUSHWICK AVENUE',
 '128 BUSHWICK AVENUE',
 '221 TEN EYCK WALK',
 '223 TEN EYCK WALK',
 '124 BUSHWICK AVENUE',
 '122 BUSHWICK AVENUE',
 '200 TEN EYCK WALK',
 '202 TEN EYCK WALK',
 '211 STAGG WALK',
 '213 STAGG WALK',
 '215 STAGG WALK',
 '222 TEN EYCK WALK',
 '224 TEN EYCK WALK',
 '226 TEN EYCK WALK',
 '233 STAGG WALK',
 '235 STAGG WALK',
 '196 STAGG WALK',
 '199 SCHOLES STREET',
 '197 SCHOLES STREET',
 '195 SCHOLES STREET',
 '201 SCHOLES STREET',
 '203 SCHOLES STREET',
 '205 SCHOLES STREET',
 '109 TEN EYCK WALK',
 '110 MAUJER STREET',
 '108 MAUJER STREET',
 '114 MAUJER STREET',
 '112 MAUJER STREET',
 '111 TEN EYCK WALK',
 '113 TEN EYCK WALK',
 '215 SCHOLES STREET',
 '218 STAGG WALK',
 '216 STAGG WALK',
 '214 STAGG WALK',
 '178 BUSHWICK AVENUE',
 '222 STAGG WALK',
 '172 BUSHWICK AVENUE',
 '220 STAGG WALK',
 '176 BUSHWICK AVENUE',
 '217 SCHOLES STREET',
 '219 SCHOLES STREET',
 '195 GRAHAM AVENUE',
 '90 TEN EYCK WALK',
 '92 TEN EYCK WALK',
 '101 STAGG WALK',
 '99 STAGG WALK',
 '97 STAGG WALK',
 '110 TEN EYCK WALK',
 '112 TEN EYCK WALK',
 '114 TEN EYCK WALK',
 '123 STAGG WALK',
 '125 STAGG WALK',
 '88 STAGG WALK',
 '95 SCHOLES STREET',
 '93 SCHOLES STREET',
 '91 SCHOLES STREET',
 '101 SCHOLES STREET',
 '99 SCHOLES STREET',
 '97 SCHOLES STREET',
 '106 STAGG WALK',
 '108 STAGG WALK',
 '110 STAGG WALK',
 '111 SCHOLES STREET',
 '115 SCHOLES STREET',
 '113 SCHOLES STREET',
 '112 STAGG WALK',
 '114 STAGG WALK',
 '123 TEN EYCK WALK',
 '125 TEN EYCK WALK',
 '126 MAUJER STREET',
 '124 MAUJER STREET',
 '128 MAUJER STREET',
 '127 TEN EYCK WALK',
 '129 TEN EYCK WALK',
 '131 TEN EYCK WALK',
 '143 TEN EYCK WALK',
 '145 TEN EYCK WALK',
 '144 MAUJER STREET',
 '239 GRAHAM AVENUE',
 '237 GRAHAM AVENUE',
 '142 MAUJER STREET',
 '146 MAUJER STREET',
 '152 MAUJER STREET',
 '243 GRAHAM AVENUE',
 '245 GRAHAM AVENUE',
 '247 GRAHAM AVENUE',
 '241 GRAHAM AVENUE',
 '147 TEN EYCK WALK',
 '235 GRAHAM AVENUE',
 '149 TEN EYCK WALK',
 '231 GRAHAM AVENUE',
 '233 GRAHAM AVENUE',
 '151 TEN EYCK WALK',
 '238 GRAHAM AVENUE',
 '161 TEN EYCK WALK',
 '240 GRAHAM AVENUE',
 '242 GRAHAM AVENUE',
 '244 GRAHAM AVENUE',
 '163 TEN EYCK WALK',
 '248 GRAHAM AVENUE',
 '246 GRAHAM AVENUE',
 '162 MAUJER STREET',
 '250 GRAHAM AVENUE',
 '252 GRAHAM AVENUE',
 '254 GRAHAM AVENUE',
 '160 MAUJER STREET',
 '164 MAUJER STREET',
 '165 TEN EYCK WALK',
 '167 TEN EYCK WALK',
 '169 TEN EYCK WALK',
 '2021 BOSTON ROAD',
 '1012 EAST 178TH STREET',
 '1030 EAST 178TH STREET',
 '1010 EAST 178TH STREET',
 '114 TAPSCOTT STREET',
 '104 TAPSCOTT STREET',
 '335 EAST 111TH STREET',
 '344 EAST 28TH STREET',
 '344GAR EAST 28TH STREET',
 '342 EAST 28TH STREET',
 '346 EAST 28TH STREET',
 '340 EAST 28TH STREET',
 '590 WARREN STREET',
 '572 WARREN STREET',
 '568 WARREN STREET',
 '565 BALTIC STREET',
 '574 WARREN STREET',
 '590 WARREN STREET -TEMPORARY ADDRESS',
 '513 GREENE AVENUE',
 '362 CLIFTON PLACE',
 '360 CLIFTON PLACE',
 '358 CLIFTON PLACE',
 '356 CLIFTON PLACE',
 '354 CLIFTON PLACE',
 '352 CLIFTON PLACE',
 '350 CLIFTON PLACE',
 '348 CLIFTON PLACE',
 '1909 AMSTERDAM AVENUE',
 '230 WEST 193RD STREET',
 '2663 HEATH AVENUE',
 '2661 HEATH AVENUE',
 '2667 HEATH AVENUE',
 '2660 BAILEY AVENUE',
 '1870 SCHIEFFELIN AVENUE',
 '1860 SCHIEFFELIN AVENUE',
 '1225 EAST 225TH STREET',
 '1871 SCHIEFFELIN PLACE',
 '1891 SCHIEFFELIN PLACE',
 '1220 EAST 229TH STREET',
 '1880 SCHIEFFELIN AVENUE',
 '1890 SCHIEFFELIN AVENUE',
 '1920 SCHIEFFELIN AVENUE',
 '1930 SCHIEFFELIN AVENUE',
 '1900 SCHIEFFELIN AVENUE',
 '1910 SCHIEFFELIN AVENUE',
 '1861 SCHIEFFELIN PLACE',
 '1881 SCHIEFFELIN PLACE',
 '1851 SCHIEFFELIN PLACE',
 '455 BARBEY STREET',
 '459 BARBEY STREET',
 '463 BARBEY STREET',
 '418 JEROME STREET',
 '422 JEROME STREET',
 '426 JEROME STREET',
 '610 BELMONT AVENUE',
 '616 BELMONT AVENUE',
 '100 SOUTH 10TH STREET',
 '447 BERRY STREET',
 '448 BERRY STREET',
 '449 BERRY STREET',
 '45 SOUTH 10TH STREET',
 '450 BERRY STREET',
 '451 BERRY STREET',
 '453 BERRY STREET',
 '455 BERRY STREET',
 '462 BEDFORD AVENUE',
 '464 BEDFORD AVENUE',
 '466 BEDFORD AVENUE',
 '49 SOUTH 10TH STREET',
 '51 SOUTH 10TH STREET',
 '53 SOUTH 10TH STREET',
 '55 SOUTH 10TH STREET',
 '57 SOUTH 10TH STREET',
 '59 SOUTH 10TH STREET',
 '61 SOUTH 10TH STREET',
 '63 SOUTH 10TH STREET',
 '65 SOUTH 10TH STREET',
 '67 SOUTH 10TH STREET',
 '74 SOUTH 9TH STREET',
 '65A SOUTH 10TH STREET',
 '440 BERRY STREET',
 '71 SOUTH 10TH STREET',
 '46 SOUTH 9TH STREET',
 '50 SOUTH 9TH STREET',
 '54 SOUTH 9TH STREET',
 '58 SOUTH 9TH STREET',
 '46 SOUTH 10TH STREET',
 '48 SOUTH 10TH STREET',
 '52 SOUTH 10TH STREET',
 '56 SOUTH 10TH STREET',
 '60 SOUTH 10TH STREET',
 '64 SOUTH 10TH STREET',
 '84 SOUTH 10TH STREET',
 '88 SOUTH 10TH STREET',
 '92 SOUTH 10TH STREET',
 '404 BROOK AVENUE',
 '510 EAST 144TH STREET',
 '400 BROOK AVENUE',
 '550 EAST 144TH STREET',
 '540 EAST 144TH STREET',
 '530 EAST 144TH STREET',
 '520 EAST 144TH STREET',
 '511 EAST 143RD STREET',
 '515 EAST 143RD STREET',
 '525 EAST 143RD STREET',
 '531 EAST 143RD STREET',
 '535 EAST 143RD STREET',
 '545 EAST 143RD STREET',
 '551 EAST 143RD STREET',
 '555 EAST 143RD STREET',
 '401 SAINT ANNS AVENUE',
 '560 EAST 144TH STREET',
 '700 EAST 140TH STREET',
 '690 EAST 140TH STREET',
 '443 EAST 137TH STREET',
 '453 EAST 137TH STREET',
 '455 EAST 137TH STREET',
 '463 EAST 137TH STREET',
 '408 EAST 137TH STREET',
 '416 EAST 137TH STREET',
 '505 EAST 144TH STREET',
 '509 EAST 144TH STREET',
 '511 EAST 144TH STREET',
 '517 EAST 144TH STREET',
 '695 EAST 139TH STREET',
 '451 EAST 136TH STREET',
 '411 EAST 136TH STREET',
 '427 SAINT ANNS AVENUE',
 '423 SAINT ANNS AVENUE',
 '480 EAST 143RD STREET',
 '490 EAST 143RD STREET',
 '433 EAST 146TH STREET',
 '435 EAST 146TH STREET',
 '437 EAST 146TH STREET',
 '439 EAST 146TH STREET',
 '441 EAST 146TH STREET',
 '513 EAST 146TH STREET',
 '511 EAST 146TH STREET',
 '417 EAST 146TH STREET',
 '419 EAST 146TH STREET',
 '421 EAST 146TH STREET',
 '423 EAST 146TH STREET',
 '425 EAST 146TH STREET',
 '427 EAST 146TH STREET',
 '429 EAST 146TH STREET',
 '431 EAST 146TH STREET',
 '527 EAST 146TH STREET',
 '545 EAST 146TH STREET',
 '547 EAST 146TH STREET',
 '537 EAST 146TH STREET',
 '512 EAST 146TH STREET',
 '510 EAST 146TH STREET',
 '530 EAST 146TH STREET',
 '528 EAST 146TH STREET',
 '455 EAST 146TH STREET',
 '450 EAST 143RD STREET',
 '521 EAST 146TH STREET',
 '525 EAST 146TH STREET',
 '521 EAST 145TH STREET',
 '525 EAST 145TH STREET',
 '400 EAST 147TH STREET',
 '460 EAST 147TH STREET',
 '550 EAST 147TH STREET',
 '474 WILLIS AVENUE',
 '465 SAINT ANNS AVENUE',
 '1943 AMSTERDAM AVENUE',
 '1945 AMSTERDAM AVENUE',
 '1949 AMSTERDAM AVENUE',
 '1947 AMSTERDAM AVENUE',
 '2440 BOSTON ROAD',
 '2430 BOSTON ROAD',
 '2424 BOSTON ROAD',
 '3475 BIVONA STREET',
 '3485 BIVONA STREET',
 '3555 BIVONA STREET',
 '3545 BIVONA STREET',
 '3565 BIVONA STREET',
 '3560 BIVONA STREET',
 '3550 BIVONA STREET',
 '3540 BIVONA STREET',
 '3580 BIVONA STREET',
 '3570 BIVONA STREET',
 '2185 REEDS MILL LANE',

<b>NOTE:</b> There's one BIN that's actually a blank, so the actual total number of unique BINs is 714.

In [9]:
## check number of BINs
all_combined['BIN#'].nunique()

715

<b>NOTE:</b> There is one item in the list below that is not an actual string of digits... so it will not show up in the later code which identifies development names and assigns those names to BBLs

In [10]:
## NOTE: there's one BBL in here without any digits...
all_combined['BBL'].nunique()

451

## Extract development names and other information about the developments

In [11]:
rows = [] ## <-- empty list for later
current_dev_name = None 
current_dev_info = None

In [12]:
for page_num, page in enumerate(pdf.pages): # <-- for each page in the document...

    texts = page.extract_text() # <-- exract every table
    lines = texts.strip().split('\n')

    for line in lines:
        if len(line) < 36 and not line.startswith('Borough'):
            current_dev_name = line
        elif line.startswith('Borough'):
            current_dev_info = line
            line_parts = current_dev_info.split(':')
            boro = line_parts[1].strip(' TOTAL UNITS')
            units = line_parts[2].strip(' TDS #')
            transfer_date = line_parts[4]
        elif re.match(r'^\d{10}', line):
            parts = line.split()
        
            row = {
                    'dev_name': current_dev_name,
                    'bbl': parts[0],
                    'boro': boro,
                    'units': units,
                    'transfer': transfer_date
                }
            rows.append(row)

dev_df = pd.DataFrame(rows)

## Merge

In [13]:
## change to lowercase
all_combined.columns = all_combined.columns.str.lower()

In [14]:
## change names
all_combined.columns

Index(['bbl', 'bldg#', 'm', 'address', 'zip code', 'cd #', 'fc #', 'ss #',
       'sa #', 'cc #', 'bin#'],
      dtype='object')

In [15]:
## change column names
all_combined = all_combined.rename(columns = {'bldg#':'bldg',
                                              'sa #':'sa',
                                              'cc #': 'cc',
                                              'cd #':'cd',
                                              'fc #':'fc',
                                              'bin#':'bin',
                                              'ss #':'ss',
                                              'address':'og_address'})

In [16]:
## merge
merged_df = pd.merge(all_combined,
                     dev_df,
                     on = 'bbl',
                     how = 'left')

## FIX NULL DEVELOPMENTS

In [17]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23069 entries, 0 to 23068
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bbl         23069 non-null  object
 1   bldg        23069 non-null  object
 2   m           23069 non-null  object
 3   og_address  23069 non-null  object
 4   zip code    23069 non-null  object
 5   cd          23069 non-null  object
 6   fc          23069 non-null  object
 7   ss          23069 non-null  object
 8   sa          23069 non-null  object
 9   cc          23069 non-null  object
 10  bin         23069 non-null  object
 11  dev_name    23045 non-null  object
 12  boro        23045 non-null  object
 13  units       23045 non-null  object
 14  transfer    23045 non-null  object
dtypes: object(15)
memory usage: 2.6+ MB

In [18]:
null_devs = merged_df[merged_df['dev_name'].isnull()].reset_index()
null_devs

,index,bbl,bldg,m,og_address,zip code,cd,fc,ss,sa,cc,bin,dev_name,boro,units,transfer
0,4136,,2,,1764 STERLING PLACE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
1,4192,,2,,1776 STERLING PLACE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
2,4217,,3,,510 HOWARD AVENUE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
3,4540,,5,,553 RALPH AVENUE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
4,4556,,5,,555 RALPH AVENUE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
5,4915,,8,,1810 STERLING PLACE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
6,4917,,8,,1812 STERLING PLACE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
7,4918,,8,,1806 STERLING PLACE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
8,12181,,1,M,344 EAST 28TH STREET,10016,06,12,59,74,02,,NaN,NaN,NaN,NaN
9,12198,,,,590 WARREN STREET,11217,06,10,26,52,39,,NaN,NaN,NaN,NaN
10,12215,,2,,590 WARREN STREET -TEMPORARY ADDRESS,,,,,,,,NaN,NaN,NaN,NaN
11,12563,,,,65A SOUTH 10TH STREET,,,,,,,,NaN,NaN,NaN,NaN
12,14017,,,,1161 ADEE AVENUE,10469,11,15,36,83,12,,NaN,NaN,NaN,NaN
13,14326,,,,1895 SCHIEFFELIN AVENUE,10466,12,16,36,83,12,,NaN,NaN,NaN,NaN
14,16051,,,,1385 FRANKLIN AVENUE,10456,03,15,32,79,16,,NaN,NaN,NaN,NaN
15,18011,,5,,ADDRESS IS NOT AVAILABLE,,,,,,,,NaN,NaN,NaN,NaN
16,18177,,,,1695 SAINT JOHNS PLACE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
17,18178,,,,1697 SAINT JOHNS PLACE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
18,18179,,,,1701 SAINT JOHNS PLACE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
19,18197,,,,1758 STERLING PLACE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
20,18210,,,,514 HOWARD AVENUE,11233,16,09,25,55,41,,NaN,NaN,NaN,NaN
21,18211,,,,,,,,,,,,NaN,NaN,NaN,NaN
22,19662,,,,188 TAPSCOTT STREET,11212,16,09,19,55,41,,NaN,NaN,NaN,NaN
23,19688,,,,N/A OAKLAND PLACE,,,,,,,,NaN,NaN,NaN,NaN

In [19]:
null_devs.og_address.unique().tolist()

['1764 STERLING PLACE',
 '1776 STERLING PLACE',
 '510 HOWARD AVENUE',
 '553 RALPH AVENUE',
 '555 RALPH AVENUE',
 '1810 STERLING PLACE',
 '1812 STERLING PLACE',
 '1806 STERLING PLACE',
 '344 EAST 28TH STREET',
 '590 WARREN STREET',
 '590 WARREN STREET -TEMPORARY ADDRESS',
 '65A SOUTH 10TH STREET',
 '1161 ADEE AVENUE',
 '1895 SCHIEFFELIN AVENUE',
 '1385 FRANKLIN AVENUE',
 'ADDRESS IS NOT AVAILABLE',
 '1695 SAINT JOHNS PLACE',
 '1697 SAINT JOHNS PLACE',
 '1701 SAINT JOHNS PLACE',
 '1758 STERLING PLACE',
 '514 HOWARD AVENUE',
 '',
 '188 TAPSCOTT STREET',
 'N/A OAKLAND PLACE']

In [20]:
dev_corrections = {'1764 STERLING PLACE':'HOWARD AVENUE-PARK PLACE',
 '1776 STERLING PLACE':'HOWARD AVENUE-PARK PLACE',
 '510 HOWARD AVENUE':'HOWARD AVENUE-PARK PLACE',
 '553 RALPH AVENUE':'HOWARD AVENUE-PARK PLACE',
 '555 RALPH AVENUE':'HOWARD AVENUE-PARK PLACE',
 '1810 STERLING PLACE':'HOWARD AVENUE-PARK PLACE',
 '1812 STERLING PLACE':'HOWARD AVENUE-PARK PLACE',
 '1806 STERLING PLACE':'HOWARD AVENUE-PARK PLACE',
 '344 EAST 28TH STREET':'344 EAST 28TH STREET',
 '590 WARREN STREET':'572 WARREN STREET',
 '590 WARREN STREET -TEMPORARY ADDRESS':'572 WARREN STREET',
 '65A SOUTH 10TH STREET':'BERRY STREET-SOUTH 9TH STREET',
 '1161 ADEE AVENUE':'EASTCHESTER GARDENS',
 '1895 SCHIEFFELIN AVENUE':'EDENWALD',
 '1385 FRANKLIN AVENUE':'FRANKLIN AVENUE II CONVENTIONAL',
 'ADDRESS IS NOT AVAILABLE':'HOPE GARDENS',
 '1695 SAINT JOHNS PLACE':'HOWARD AVENUE-PARK PLACE',
 '1697 SAINT JOHNS PLACE':'HOWARD AVENUE-PARK PLACE',
 '1701 SAINT JOHNS PLACE':'HOWARD AVENUE-PARK PLACE',
 '1758 STERLING PLACE':'HOWARD AVENUE-PARK PLACE',
 '514 HOWARD AVENUE':'HOWARD AVENUE-PARK PLACE',
 '':'HOWARD AVENUE-PARK PLACE',
 '188 TAPSCOTT STREET':'TAPSCOTT STREET REHAB',
 'N/A OAKLAND PLACE':'TWIN PARKS EAST (SITE 9)',
 ## the ones below are fixing some kind of dev mixup that happened along the way
 '699 EAST 139TH STREET':'BETANCES III, 13',
 '695 EAST 139TH STREET':'BETANCES III, 13',
 '3340 BAILEY AVENUE':'FORT INDEPENDENCE STREET-HEATH AVENUE',
 '3350 BAILEY AVENUE':'FORT INDEPENDENCE STREET-HEATH AVENUE',
 '3353 FORT INDEPENDENCE STREET':'FORT INDEPENDENCE STREET-HEATH AVENUE',
 '3355 FORT INDEPENDENCE STREET':'FORT INDEPENDENCE STREET-HEATH AVENUE',
 '120 EAST 123RD STREET':'PARK AVENUE-EAST 122ND, 123RD STREETS',
 '115 EAST 122ND STREET':'PARK AVENUE-EAST 122ND, 123RD STREETS',
 '114 EAST 123RD STREET':'PARK AVENUE-EAST 122ND, 123RD STREETS',
 '116 EAST 123RD STREET':'PARK AVENUE-EAST 122ND, 123RD STREETS',
 '1487 SAINT JOHNS PLACE':'STERLING PLACE REHABS (SAINT JOHNS-STERLING)',
'1483 SAINT JOHNS PLACE':'STERLING PLACE REHABS (SAINT JOHNS-STERLING)',
'1491 SAINT JOHNS PLACE':'STERLING PLACE REHABS (SAINT JOHNS-STERLING)',
'1506 STERLING PLACE':'STERLING PLACE REHABS (SAINT JOHNS-STERLING)',
'1511 STERLING PLACE':'STERLING PLACE REHABS (SAINT JOHNS-STERLING)',
'1640 STERLING PLACE':'STERLING PLACE REHABS (SAINT JOHNS-STERLING)',
'1448 STERLING PLACE':'STERLING PLACE REHABS (STERLING-BUFFALO)',
'1452 STERLING PLACE':'STERLING PLACE REHABS (STERLING-BUFFALO)',
'1568 STERLING PLACE':'STERLING PLACE REHABS (STERLING-BUFFALO)',
'1578 STERLING PLACE':'STERLING PLACE REHABS (STERLING-BUFFALO)',
'1588 STERLING PLACE':'STERLING PLACE REHABS (STERLING-BUFFALO)',
'1598 STERLING PLACE':'STERLING PLACE REHABS (STERLING-BUFFALO)',
'225 BUFFALO AVENUE':'STERLING PLACE REHABS (STERLING-BUFFALO)',
'450 WEST 164TH STREET':'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
'457 WEST 164TH STREET':'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
'461 WEST 164TH STREET':'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
'463 WEST 164TH STREET':'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
'465 WEST 164TH STREET':'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
'500 WEST 164TH STREET':'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
'2111 AMSTERDAM AVENUE':'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
'2109 AMSTERDAM AVENUE':'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
'545 WEST 156TH STREET':'WASHINGTON HEIGHTS REHAB PHASE III (HARLEM RIVER)',
'502 WEST 177TH STREET':'WASHINGTON HEIGHTS REHAB PHASE IV (C)',
'506 WEST 176TH STREET':'WASHINGTON HEIGHTS REHAB PHASE IV (C)',
'510 WEST 176TH STREET':'WASHINGTON HEIGHTS REHAB PHASE IV (D)',
'514 WEST 176TH STREET':'WASHINGTON HEIGHTS REHAB PHASE IV (D)',
'157 ALASKA STREET':'WEST BRIGHTON II',
'155 ALASKA STREET':'WEST BRIGHTON II',
'1115 CASTLETON AVENUE':'WEST BRIGHTON II',
'1085 CASTLETON AVENUE':'WEST BRIGHTON II',
'1083 CASTLETON AVENUE':'WEST BRIGHTON II',
'1065 CASTLETON AVENUE':'WEST BRIGHTON II',
'260 BROADWAY':'WEST BRIGHTON II',
'244 BROADWAY':'WEST BRIGHTON II',
'159 ALASKA STREET':'WEST BRIGHTON II',
'501 WEST 176TH STREET':'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
'2340 AMSTERDAM AVENUE':'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
'2346 AMSTERDAM AVENUE':'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
'500 WEST 177TH STREET':'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
'503 WEST 177TH STREET':'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
'511 WEST 177TH STREET':'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
'514 WEST 177TH STREET':'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
'506 WEST 177TH STREET':'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
'509 WEST 176TH STREET':'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',}

In [21]:
for addresses,dev_names in dev_corrections.items():
    merged_df.loc[merged_df['og_address'] == addresses, 'dev_name'] = dev_names

In [22]:
## but the right number of addresses and bins
print(f'number of unique address: {merged_df.og_address.nunique()} \nnumber of unique bins: {merged_df.bin.nunique()}')

number of unique address: 1538
number of unique bins: 715

In [23]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23069 entries, 0 to 23068
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bbl         23069 non-null  object
 1   bldg        23069 non-null  object
 2   m           23069 non-null  object
 3   og_address  23069 non-null  object
 4   zip code    23069 non-null  object
 5   cd          23069 non-null  object
 6   fc          23069 non-null  object
 7   ss          23069 non-null  object
 8   sa          23069 non-null  object
 9   cc          23069 non-null  object
 10  bin         23069 non-null  object
 11  dev_name    23069 non-null  object
 12  boro        23045 non-null  object
 13  units       23045 non-null  object
 14  transfer    23045 non-null  object
dtypes: object(15)
memory usage: 2.6+ MB

## CLEANING

In [24]:
## take a look at development names first
merged_df.dev_name.unique()

array(['ARMSTRONG I', 'ARMSTRONG II', '65A SOUTH 10TH STREET',
       'BETANCES III, 13', 'BETANCES IV', 'BETANCES V', 'BOULEVARD',
       'BUSHWICK II (GROUPS A & C)', 'BUSHWICK II CDA (GROUP E)',
       'CROWN HEIGHTS', 'EASTCHESTER GARDENS', 'EDENWALD',
       'FENIMORE-LEFFERTS', 'FRANKLIN AVENUE II CONVENTIONAL',
       'HARLEM RIVER', 'HOWARD AVENUE', 'HOWARD AVENUE-PARK PLACE',
       'LINDEN', 'OCEAN BAY APARTMENTS (BAYSIDE)', 'PARK ROCK REHAB',
       'SAMUEL (CITY)', 'SOUTH BRONX AREA (SITE 402)',
       'TWIN PARKS WEST (SITES 1 & 2)', 'WEEKSVILLE GARDENS',
       'WILLIAMS PLAZA', 'WILLIAMSBURG', '1010 EAST 178TH STREET',
       '104-14 TAPSCOTT STREET', '335 EAST 111TH STREET',
       '344 EAST 28TH STREET', '572 WARREN STREET', 'AUDUBON',
       'BAILEY AVENUE-WEST 193RD STREET', 'BAYCHESTER',
       'BELMONT-SUTTER AREA', 'BERRY STREET-SOUTH 9TH STREET',
       'BETANCES I', 'BETANCES II, 13', 'BETANCES II, 18',
       'BETANCES III, 18', 'BETANCES II, 9A', 'BETANCES III, 9A',
       'BETANCES VI', 'BETHUNE GARDENS', 'BOSTON ROAD PLAZA',
       'BOSTON SECOR', 'BUSHWICK II (GROUPS B & D)',
       'CLAREMONT PARKWAY-FRANKLIN AVENUE', 'DAVIDSON',
       'EAGLE AVENUE-EAST 163RD STREET',
       'EAST 180TH STREET-MONTEREY AVENUE', 'FIORENTINO PLAZA',
       'FORT INDEPENDENCE STREET-HEATH AVENUE',
       'FORT WASHINGTON AVENUE REHAB', 'FRANKLIN AVENUE I CONVENTIONAL',
       'FRANKLIN AVENUE III CONVENTIONAL', 'GRAMPION', 'HARLEM RIVER II',
       'HARRISON AVENUE REHAB (GROUP A)',
       'HARRISON AVENUE REHAB (GROUP B)',
       'HIGHBRIDGE REHABS (ANDERSON AVENUE)',
       'HIGHBRIDGE REHABS (NELSON AVENUE)', 'HOPE GARDENS',
       'INDEPENDENCE', 'LENOX ROAD-ROCKAWAY PARKWAY', 'MANHATTANVILLE',
       'MANHATTANVILLE REHAB (GROUP 2)', 'MANHATTANVILLE REHAB (GROUP 3)',
       'MARCY AVENUE-GREENE AVENUE SITE A',
       'MARCY AVENUE-GREENE AVENUE SITE B', 'MARSHALL PLAZA',
       'MIDDLETOWN PLAZA', 'MURPHY', 'OCEAN HILL-BROWNSVILLE',
       'PALMETTO GARDENS', 'PARK AVENUE-EAST 122ND, 123RD STREETS',
       'PENNSYLVANIA AVENUE-WORTMAN AVENUE',
       'PUBLIC SCHOOL 139 (CONVERSION)', 'RALPH AVENUE REHAB',
       'REID APARTMENTS', 'RUTLAND TOWERS', 'SACK WERN',
       'SAMUEL (MHOP) I', 'SAMUEL (MHOP) II', 'SAMUEL (MHOP) III',
       'STEBBINS AVENUE-HEWITT PLACE',
       'STERLING PLACE REHABS (SAINT JOHNS-STERLING)',
       'STERLING PLACE REHABS (STERLING-BUFFALO)',
       'SUTTER AVENUE-UNION STREET', 'TAPSCOTT STREET REHAB',
       'TWIN PARKS EAST (SITE 9)', 'N/A OAKLAND PLACE',
       'UNION AVENUE-EAST 163RD STREET', 'UNION AVENUE-EAST 166TH STREET',
       'UNIVERSITY AVENUE REHAB', 'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
       'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
       'WASHINGTON HEIGHTS REHAB PHASE III (HARLEM RIVER)',
       'WASHINGTON HEIGHTS REHAB PHASE IV (C)',
       'WASHINGTON HEIGHTS REHAB PHASE IV (D)', 'WEST BRIGHTON I',
       'WEST BRIGHTON II', 'WISE TOWERS'], dtype=object)

In [25]:
test = merged_df[merged_df['dev_name'] == 'TWIN PARKS WEST (SITES 1 & 2)']
test.head()

,bbl,bldg,m,og_address,zip code,cd,fc,ss,sa,cc,bin,dev_name,boro,units,transfer
5696,2031430155,1,,360 FORD STREET,10457,05,15,33,86,15,2092394,TWIN PARKS WEST (SITES 1 & 2),BRONX,312,10/31/2018
5697,2031430155,1,,360 FORD STREET,10457,05,15,33,86,15,2092394,TWIN PARKS WEST (SITES 1 & 2),BRONX,312,10/31/2018
5698,2031430155,1,,360 FORD STREET,10457,05,15,33,86,15,2092394,TWIN PARKS WEST (SITES 1 & 2),BRONX,312,10/31/2018
5699,2031430155,1,,360 FORD STREET,10457,05,15,33,86,15,2092394,TWIN PARKS WEST (SITES 1 & 2),BRONX,312,10/31/2018
5700,2031430155,1,,360 FORD STREET,10457,05,15,33,86,15,2092394,TWIN PARKS WEST (SITES 1 & 2),BRONX,312,10/31/2018

In [26]:
## dict of corrections
dev_corrections = {"65A SOUTH 10TH STREET":"BERRY STREET-SOUTH 9TH STREET",
                   "N/A OAKLAND PLACE":"TWIN PARKS EAST (SITE 9)"}

In [27]:
## apply the corrections
merged_df['dev_name'] = merged_df['dev_name'].replace(dev_corrections)
merged_df = merged_df.reset_index(drop = True)

In [28]:
merged_df.boro.unique()

array(['BROOKLY', 'BRONX', 'MANH', nan, 'QUEE', 'EN ISLAND'], dtype=object)

In [29]:
## now move onto boros
boro_corrections = {'BROOKLY':'brooklyn',
                    'BRONX':'bronx',
                    'MANH':'manhattan',
                    'QUEE':'queens',
                    'EN ISLAND':'staten island'}

In [30]:
## apply the corrections
merged_df['boro'] = merged_df['boro'].replace(boro_corrections)
merged_df = merged_df.reset_index(drop = True)

In [31]:
## now addresses
merged_df.og_address.unique().tolist()

['346 CLIFTON PLACE',
 '344 CLIFTON PLACE',
 '360 NOSTRAND AVENUE',
 '260 LEXINGTON AVENUE',
 '262 LEXINGTON AVENUE',
 '264 LEXINGTON AVENUE',
 '254 LEXINGTON AVENUE',
 '252 LEXINGTON AVENUE',
 '252A LEXINGTON AVENUE',
 '250 LEXINGTON AVENUE',
 '366 CLIFTON PLACE',
 '380 CLIFTON PLACE',
 '388 CLIFTON PLACE',
 '396 CLIFTON PLACE',
 '545 GREENE AVENUE',
 '555 GREENE AVENUE',
 '304 LEXINGTON AVENUE',
 '302 LEXINGTON AVENUE',
 '300 LEXINGTON AVENUE',
 '298 LEXINGTON AVENUE',
 '296 LEXINGTON AVENUE',
 '294 LEXINGTON AVENUE',
 '292 LEXINGTON AVENUE',
 '290 LEXINGTON AVENUE',
 '288 LEXINGTON AVENUE',
 '286 LEXINGTON AVENUE',
 '284 LEXINGTON AVENUE',
 '282 LEXINGTON AVENUE',
 '280 LEXINGTON AVENUE',
 '278 LEXINGTON AVENUE',
 '310 LEXINGTON AVENUE',
 '320 LEXINGTON AVENUE',
 '330 LEXINGTON AVENUE',
 '336 LEXINGTON AVENUE',
 '435 GATES AVENUE',
 '441 GATES AVENUE',
 '447 GATES AVENUE',
 '449 GATES AVENUE',
 '451 GATES AVENUE',
 '453 GATES AVENUE',
 '455 GATES AVENUE',
 '457 GATES AVENUE',
 '459 GATES AVENUE',
 '461 GATES AVENUE',
 '463 GATES AVENUE',
 '465 GATES AVENUE',
 '467 GATES AVENUE',
 '469 GATES AVENUE',
 '471 GATES AVENUE',
 '473 GATES AVENUE',
 '475 GATES AVENUE',
 '375 LEXINGTON AVENUE',
 '385 LEXINGTON AVENUE',
 '395 LEXINGTON AVENUE',
 '405 LEXINGTON AVENUE',
 '415 LEXINGTON AVENUE',
 '280 TOMPKINS AVENUE',
 '360 LEXINGTON AVENUE',
 '370 LEXINGTON AVENUE',
 '380 LEXINGTON AVENUE',
 '390 LEXINGTON AVENUE',
 '775 MARCY AVENUE',
 '785 MARCY AVENUE',
 '791 MARCY AVENUE',
 '499 GATES AVENUE',
 '505 GATES AVENUE',
 '515 GATES AVENUE',
 '495 GATES AVENUE',
 '96 SOUTH 10TH STREET',
 '699 EAST 139TH STREET',
 '409 EAST 146TH STREET',
 '411 EAST 146TH STREET',
 '413 EAST 146TH STREET',
 '415 EAST 146TH STREET',
 '445 EAST 146TH STREET',
 '785 SCHENCK AVENUE',
 '2150 LINDEN BOULEVARD',
 '797 SCHENCK AVENUE',
 '842 ASHFORD STREET',
 '773 STANLEY AVENUE',
 '854 ASHFORD STREET',
 '845 SCHENCK AVENUE',
 '857 SCHENCK AVENUE',
 '881 SCHENCK AVENUE',
 '893 SCHENCK AVENUE',
 '726 STANLEY AVENUE',
 '738 STANLEY AVENUE',
 '740 STANLEY AVENUE',
 '359 WORTMAN AVENUE',
 '357 WORTMAN AVENUE',
 '756 STANLEY AVENUE',
 '758 STANLEY AVENUE',
 '772 STANLEY AVENUE',
 '363 WORTMAN AVENUE',
 '361 WORTMAN AVENUE',
 '872 ASHFORD STREET',
 '884 ASHFORD STREET',
 '908 ASHFORD STREET',
 '920 ASHFORD STREET',
 '817 SCHENCK AVENUE',
 '829 SCHENCK AVENUE',
 '2156 LINDEN BOULEVARD',
 '807 SCHENCK AVENUE',
 '725 STANLEY AVENUE',
 '2202 LINDEN BOULEVARD',
 '830 ASHFORD STREET',
 '765 STANLEY AVENUE',
 '812 ASHFORD STREET',
 '828 ASHFORD STREET',
 '804 ASHFORD STREET',
 '816 ASHFORD STREET',
 '1280 GREENE AVENUE',
 '1240 GREENE AVENUE',
 '289 CENTRAL AVENUE',
 '595 EVERGREEN AVENUE',
 '615 EVERGREEN AVENUE',
 '690 EVERGREEN AVENUE',
 '670 EVERGREEN AVENUE',
 '85 COVERT STREET',
 '75 COVERT STREET',
 '160 HIMROD STREET',
 '234 GROVE STREET',
 '230 GROVE STREET',
 '226 GROVE STREET',
 '339 WILSON AVENUE',
 '343 WILSON AVENUE',
 '347 WILSON AVENUE',
 '235 LINDEN STREET',
 '239 LINDEN STREET',
 '243 LINDEN STREET',
 '247 LINDEN STREET',
 '251 LINDEN STREET',
 '532 KNICKERBOCKER AVENUE',
 '528 KNICKERBOCKER AVENUE',
 '524 KNICKERBOCKER AVENUE',
 '236 LINDEN STREET',
 '232 LINDEN STREET',
 '228 LINDEN STREET',
 '224 LINDEN STREET',
 '220 LINDEN STREET',
 '357 WILSON AVENUE',
 '361 WILSON AVENUE',
 '365 WILSON AVENUE',
 '1389 GATES AVENUE',
 '1393 GATES AVENUE',
 '1397 GATES AVENUE',
 '1411 GATES AVENUE',
 '1415 GATES AVENUE',
 '558 KNICKERBOCKER AVENUE',
 '554 KNICKERBOCKER AVENUE',
 '550 KNICKERBOCKER AVENUE',
 '1371 SAINT MARKS AVENUE',
 '1629 PARK PLACE',
 '1630 PARK PLACE',
 '1636 PARK PLACE',
 '1640 PARK PLACE',
 '1646 PARK PLACE',
 '1240 BURKE AVENUE',
 '1246 BURKE AVENUE',
 '1260 BURKE AVENUE',
 '3055 BOUCK AVENUE',
 '1255 ADEE AVENUE',
 '1245 ADEE AVENUE',
 '1221 ADEE AVENUE',
 '1219 ADEE AVENUE',
 '1160 229TH DRIVE SOUTH',
 '1187 226TH DRIVE',
 '1183 226TH DRIVE',
 '1169 226TH DRIVE',
 '1165 226TH DRIVE',
 '1151 226TH DRIVE',
 '1145 226TH DRIVE',
 '1141 226TH DRIVE',
 '1131 226TH DRIVE',
 '1135 226TH DRIVE',
 '4000 LACONIA AVENUE',
 '4010 LACONIA AVENUE',
 '1115 EAST 225TH STREET',
 '1121 EAST 225TH STREET',
 '1138 226TH DRIVE',
 '1130 226TH DRIVE',
 '1155 EAST 225TH STREET',
 '1161 EAST 225TH STREET',
 '1181 EAST 225TH STREET',
 '1175 EAST 225TH STREET',
 '3841 BAYCHESTER AVENUE',
 '3845 BAYCHESTER AVENUE',
 '1195 EAST 225TH STREET',
 '1855 SCHIEFFELIN AVENUE',
 '1140 EAST 229TH STREET',
 '1150 EAST 229TH STREET',
 '1149GAR 229TH DRIVE NORTH',
 '1981 SCHIEFFELIN AVENUE',
 '1985 SCHIEFFELIN AVENUE',
 '1961 SCHIEFFELIN AVENUE',
 '1965 SCHIEFFELIN AVENUE',
 '1173 229TH DRIVE NORTH',
 '1161 229TH DRIVE NORTH',
 '1159 229TH DRIVE NORTH',
 '1147 229TH DRIVE NORTH',
 '1149 229TH DRIVE NORTH',
 '738 FENIMORE STREET',
 '736 FENIMORE STREET',
 '732 FENIMORE STREET',
 '1390 FRANKLIN AVENUE',
 '58 MACOMBS PLACE',
 '56 1/2 MACOMBS PLACE',
 '54 1/2 MACOMBS PLACE',
 '52 MACOMBS PLACE',
 '56 MACOMBS PLACE',
 '50 MACOMBS PLACE',
 '48 MACOMBS PLACE',
 '46 MACOMBS PLACE',
 '40 1/2 MACOMBS PLACE',
 '42 MACOMBS PLACE',
 '42 1/2 MACOMBS PLACE',
 '44 MACOMBS PLACE',
 '2653 A C POWELL BOULEVARD',
 '2651 A C POWELL BOULEVARD',
 '2645 A C POWELL BOULEVARD',
 '2641 A C POWELL BOULEVARD',
 '187 WEST 152ND STREET',
 '183 WEST 152ND STREET',
 '180 WEST 152ND STREET',
 '182 WEST 152ND STREET',
 '186 WEST 152ND STREET',
 '2637 A C POWELL BOULEVARD',
 '190 WEST 152ND STREET',
 '2627 A C POWELL BOULEVARD',
 '191W WEST 151ST STREET',
 '2633 A C POWELL BOULEVARD',
 '2621 A C POWELL BOULEVARD',
 '191V WEST 151ST STREET',
 '191U WEST 151ST STREET',
 '181 WEST 151ST STREET',
 '177 WEST 151ST STREET',
 '173 WEST 151ST STREET',
 '578 HOWARD AVENUE',
 '582 HOWARD AVENUE',
 '602 HOWARD AVENUE',
 '606 HOWARD AVENUE',
 '610 HOWARD AVENUE',
 '614 HOWARD AVENUE',
 '1 TAPSCOTT STREET',
 '5 TAPSCOTT STREET',
 '9 TAPSCOTT STREET',
 '13 TAPSCOTT STREET',
 '17 TAPSCOTT STREET',
 '48REAR GRAFTON STREET',
 '1764 STERLING PLACE',
 '1766A STERLING PLACE',
 '1766B STERLING PLACE',
 '1768 STERLING PLACE',
 '1768A STERLING PLACE',
 '1768B STERLING PLACE',
 '1770 STERLING PLACE',
 '1770A STERLING PLACE',
 '1770B STERLING PLACE',
 '1772 STERLING PLACE',
 '1772A STERLING PLACE',
 '1772B STERLING PLACE',
 '1774 STERLING PLACE',
 '1774A STERLING PLACE',
 '498 HOWARD AVENUE',
 '1774B STERLING PLACE',
 '1776 STERLING PLACE',
 '504 HOWARD AVENUE',
 '504A HOWARD AVENUE',
 '504B HOWARD AVENUE',
 '506 HOWARD AVENUE',
 '506A HOWARD AVENUE',
 '506B HOWARD AVENUE',
 '508 HOWARD AVENUE',
 '508A HOWARD AVENUE',
 '510 HOWARD AVENUE',
 '508B HOWARD AVENUE',
 '1679 SAINT JOHNS PLACE',
 '1679A SAINT JOHNS PLACE',
 '1679B SAINT JOHNS PLACE',
 '1681 SAINT JOHNS PLACE',
 '1681A SAINT JOHNS PLACE',
 '1681B SAINT JOHNS PLACE',
 '1683 SAINT JOHNS PLACE',
 '1683A SAINT JOHNS PLACE',
 '1683B SAINT JOHNS PLACE',
 '1685 SAINT JOHNS PLACE',
 '1685A SAINT JOHNS PLACE',
 '1685B SAINT JOHNS PLACE',
 '1687 SAINT JOHNS PLACE',
 '1687A SAINT JOHNS PLACE',
 '1687B SAINT JOHNS PLACE',
 '1689 SAINT JOHNS PLACE',
 '1689A SAINT JOHNS PLACE',
 '1689B SAINT JOHNS PLACE',
 '1691 SAINT JOHNS PLACE',
 '1691A SAINT JOHNS PLACE',
 '1691B SAINT JOHNS PLACE',
 '1693 SAINT JOHNS PLACE',
 '1693A SAINT JOHNS PLACE',
 '1693B SAINT JOHNS PLACE',
 '537 RALPH AVENUE',
 '537A RALPH AVENUE',
 '537B RALPH AVENUE',
 '539 RALPH AVENUE',
 '539A RALPH AVENUE',
 '539B RALPH AVENUE',
 '1702 STERLING PLACE',
 '1716 STERLING PLACE',
 '541 RALPH AVENUE',
 '541A RALPH AVENUE',
 '541B RALPH AVENUE',
 '543 RALPH AVENUE',
 '543A RALPH AVENUE',
 '543B RALPH AVENUE',
 '545 RALPH AVENUE',
 '545A RALPH AVENUE',
 '545B RALPH AVENUE',
 '547 RALPH AVENUE',
 '547A RALPH AVENUE',
 '547B RALPH AVENUE',
 '549 RALPH AVENUE',
 '549A RALPH AVENUE',
 '549B RALPH AVENUE',
 '551 RALPH AVENUE',
 '551A RALPH AVENUE',
 '553 RALPH AVENUE',
 '551B RALPH AVENUE',
 '555 RALPH AVENUE',
 '1651 SAINT JOHNS PLACE',
 '1659 SAINT JOHNS PLACE',
 '1649 SAINT JOHNS PLACE',
 '1720 STERLING PLACE',
 '1720A STERLING PLACE',
 '1720B STERLING PLACE',
 '1722 STERLING PLACE',
 '1722A STERLING PLACE',
 '1722B STERLING PLACE',
 '1724 STERLING PLACE',
 '1724A STERLING PLACE',
 '1724B STERLING PLACE',
 '1726 STERLING PLACE',
 '1726A STERLING PLACE',
 '1726B STERLING PLACE',
 '1728 STERLING PLACE',
 '1728A STERLING PLACE',
 '1728B STERLING PLACE',
 '1730 STERLING PLACE',
 '1730A STERLING PLACE',
 '1730B STERLING PLACE',
 '1732 STERLING PLACE',
 '1732A STERLING PLACE',
 '1732B STERLING PLACE',
 '1734 STERLING PLACE',
 '1734A STERLING PLACE',
 '1734B STERLING PLACE',
 '1736 STERLING PLACE',
 '1736A STERLING PLACE',
 '1736B STERLING PLACE',
 '497 HOWARD AVENUE',
 '497A HOWARD AVENUE',
 '497B HOWARD AVENUE',
 '499 HOWARD AVENUE',
 '499A HOWARD AVENUE',
 '499B HOWARD AVENUE',
 '501 HOWARD AVENUE',
 '501A HOWARD AVENUE',
 '501B HOWARD AVENUE',
 '503 HOWARD AVENUE',
 '503A HOWARD AVENUE',
 '503B HOWARD AVENUE',
 '505 HOWARD AVENUE',
 '505A HOWARD AVENUE',
 '505B HOWARD AVENUE',
 '507 HOWARD AVENUE',
 '507A HOWARD AVENUE',
 '507B HOWARD AVENUE',
 '509 HOWARD AVENUE',
 '509A HOWARD AVENUE',
 '509B HOWARD AVENUE',
 '511 HOWARD AVENUE',
 '511A HOWARD AVENUE',
 '513 HOWARD AVENUE',
 '515 HOWARD AVENUE',
 '1745 SAINT JOHNS PLACE',
 '1737 SAINT JOHNS PLACE',
 '511B HOWARD AVENUE',
 '1790 STERLING PLACE',
 '1790A STERLING PLACE',
 '1790B STERLING PLACE',
 '1792 STERLING PLACE',
 '1792A STERLING PLACE',
 '1792B STERLING PLACE',
 '1794 STERLING PLACE',
 '1794A STERLING PLACE',
 '1794B STERLING PLACE',
 '1796 STERLING PLACE',
 '1796A STERLING PLACE',
 '1796B STERLING PLACE',
 '1798 STERLING PLACE',
 '1798A STERLING PLACE',
 '1798B STERLING PLACE',
 '1800 STERLING PLACE',
 '1800A STERLING PLACE',
 '1800B STERLING PLACE',
 '1802 STERLING PLACE',
 '1802A STERLING PLACE',
 '1802B STERLING PLACE',
 '1804 STERLING PLACE',
 '1804A STERLING PLACE',
 '1804B STERLING PLACE',
 '1810 STERLING PLACE',
 '1814 STERLING PLACE',
 '1812 STERLING PLACE',
 '1806 STERLING PLACE',
 '914 VAN SICLEN AVENUE',
 '225 WORTMAN AVENUE',
 '215 WORTMAN AVENUE',
 '185 WORTMAN AVENUE',
 '187 WORTMAN AVENUE',
 '183 WORTMAN AVENUE',
 '180 WORTMAN AVENUE',
 '54-30 BEACH CHANNEL DRIVE',
 '56-10 BEACH CHANNEL DRIVE',
 '56-16 BEACH CHANNEL DRIVE',
 '54-75 ALMEDA AVENUE',
 '414 BEACH 58TH STREET',
 '57-10 BEACH CHANNEL DRIVE',
 '441 BEACH 51ST STREET',
 '445 BEACH 51ST STREET',
 '434 BEACH 54TH STREET',
 '440 BEACH 54TH STREET',
 '430 BEACH 54TH STREET',
 '444 BEACH 54TH STREET',
 '439 BEACH 54TH STREET',
 '447 BEACH 54TH STREET',
 '443 BEACH 54TH STREET',
 '434 BEACH 58TH STREET',
 '440 BEACH 58TH STREET',
 '54-49 ALMEDA AVENUE',
 '54-41 ALMEDA AVENUE',
 '54-15 ALMEDA AVENUE',
 '54-09 ALMEDA AVENUE',
 '51-49 ALMEDA AVENUE',
 '51-45 ALMEDA AVENUE',
 '51-15 ALMEDA AVENUE',
 '1474 PARK PLACE',
 '1484 PARK PLACE',
 '1480 PARK PLACE',
 '208 ROCHESTER AVENUE',
 '218 ROCHESTER AVENUE',
 '1521 STERLING PLACE',
 '1522 STERLING PLACE',
 '230 ROCHESTER AVENUE',
 '232 ROCHESTER AVENUE',
 '234 ROCHESTER AVENUE',
 '117 WEST 144TH STREET',
 '143 WEST 142ND STREET',
 '145 WEST 142ND STREET',
 '149 WEST 142ND STREET',
 '2453 A C POWELL BOULEVARD',
 '2449 A C POWELL BOULEVARD',
 '2441 A C POWELL BOULEVARD',
 '144 WEST 141ST STREET',
 '2409 A C POWELL BOULEVARD',
 '2407 A C POWELL BOULEVARD',
 '125 WEST 144TH STREET',
 '116 WEST 139TH STREET',
 '112 WEST 139TH STREET',
 '669 LENOX AVENUE',
 '103 WEST 143RD STREET',
 '105 WEST 143RD STREET',
 '129 WEST 144TH STREET',
 '133 WEST 144TH STREET',
 '148 WEST 144TH STREET',
 '158 WEST 144TH STREET',
 '162 WEST 144TH STREET',
 '825 CAULDWELL AVENUE',
 '829 CAULDWELL AVENUE',
 '611 EAST 158TH STREET',
 '615 EAST 158TH STREET',
 '625 EAST 158TH STREET',
 '635 EAST 158TH STREET',
 '645 EAST 158TH STREET',
 '854 EAGLE AVENUE',
 '850 EAGLE AVENUE',
 '844 EAGLE AVENUE',
 '840 EAGLE AVENUE',
 '834 EAGLE AVENUE',
 '830 EAGLE AVENUE',
 '360 FORD STREET',
 '365 FORD STREET, WING A',
 '365 FORD STREET, WING B',
 '353 FORD STREET',
 '355 FORD STREET',
 '365 FORD STREET, WING C',
 '365 FORD STREET',
 '365 EAST 183RD STREET, WING D',
 '365 EAST 183RD STREET, WING E',
 '355 EAST 183RD STREET',
 '365 EAST 183RD STREET, WING F',
 '1575 DEAN STREET',
 '87 TROY AVENUE',
 '1620 PACIFIC STREET',
 '1630 PACIFIC STREET',
 '1640 PACIFIC STREET',
 '1642 PACIFIC STREET',
 '1650 PACIFIC STREET',
 '1660 PACIFIC STREET',
 '1670 PACIFIC STREET',
 '1672 PACIFIC STREET',
 '80 SCHENECTADY AVENUE',
 '188 MARCY AVENUE',
 '190 MARCY AVENUE',
 '227 DIVISION AVENUE',
 '221 DIVISION AVENUE',
 '225 DIVISION AVENUE',
 '223 DIVISION AVENUE',
 '171 SCHOLES STREET',
 '181 SCHOLES STREET',
 '182 STAGG WALK',
 '180 STAGG WALK',
 '178 STAGG WALK',
 '186 STAGG WALK',
 '184 STAGG WALK',
 '183 SCHOLES STREET',
 '185 SCHOLES STREET',
 '197 TEN EYCK WALK',
 '199 TEN EYCK WALK',
 '198 MAUJER STREET',
 '196 MAUJER STREET',
 '200 MAUJER STREET',
 '201 TEN EYCK WALK',
 '203 TEN EYCK WALK',
 '205 TEN EYCK WALK',
 '219 TEN EYCK WALK',
 '216 MAUJER STREET',
 '214 MAUJER STREET',
 '220 MAUJER STREET',
 '138 BUSHWICK AVENUE',
 '136 BUSHWICK AVENUE',
 '218 MAUJER STREET',
 '134 BUSHWICK AVENUE',
 '132 BUSHWICK AVENUE',
 '130 BUSHWICK AVENUE',
 '128 BUSHWICK AVENUE',
 '221 TEN EYCK WALK',
 '223 TEN EYCK WALK',
 '124 BUSHWICK AVENUE',
 '122 BUSHWICK AVENUE',
 '200 TEN EYCK WALK',
 '202 TEN EYCK WALK',
 '211 STAGG WALK',
 '213 STAGG WALK',
 '215 STAGG WALK',
 '222 TEN EYCK WALK',
 '224 TEN EYCK WALK',
 '226 TEN EYCK WALK',
 '233 STAGG WALK',
 '235 STAGG WALK',
 '196 STAGG WALK',
 '199 SCHOLES STREET',
 '197 SCHOLES STREET',
 '195 SCHOLES STREET',
 '201 SCHOLES STREET',
 '203 SCHOLES STREET',
 '205 SCHOLES STREET',
 '109 TEN EYCK WALK',
 '110 MAUJER STREET',
 '108 MAUJER STREET',
 '114 MAUJER STREET',
 '112 MAUJER STREET',
 '111 TEN EYCK WALK',
 '113 TEN EYCK WALK',
 '215 SCHOLES STREET',
 '218 STAGG WALK',
 '216 STAGG WALK',
 '214 STAGG WALK',
 '178 BUSHWICK AVENUE',
 '222 STAGG WALK',
 '172 BUSHWICK AVENUE',
 '220 STAGG WALK',
 '176 BUSHWICK AVENUE',
 '217 SCHOLES STREET',
 '219 SCHOLES STREET',
 '195 GRAHAM AVENUE',
 '90 TEN EYCK WALK',
 '92 TEN EYCK WALK',
 '101 STAGG WALK',
 '99 STAGG WALK',
 '97 STAGG WALK',
 '110 TEN EYCK WALK',
 '112 TEN EYCK WALK',
 '114 TEN EYCK WALK',
 '123 STAGG WALK',
 '125 STAGG WALK',
 '88 STAGG WALK',
 '95 SCHOLES STREET',
 '93 SCHOLES STREET',
 '91 SCHOLES STREET',
 '101 SCHOLES STREET',
 '99 SCHOLES STREET',
 '97 SCHOLES STREET',
 '106 STAGG WALK',
 '108 STAGG WALK',
 '110 STAGG WALK',
 '111 SCHOLES STREET',
 '115 SCHOLES STREET',
 '113 SCHOLES STREET',
 '112 STAGG WALK',
 '114 STAGG WALK',
 '123 TEN EYCK WALK',
 '125 TEN EYCK WALK',
 '126 MAUJER STREET',
 '124 MAUJER STREET',
 '128 MAUJER STREET',
 '127 TEN EYCK WALK',
 '129 TEN EYCK WALK',
 '131 TEN EYCK WALK',
 '143 TEN EYCK WALK',
 '145 TEN EYCK WALK',
 '144 MAUJER STREET',
 '239 GRAHAM AVENUE',
 '237 GRAHAM AVENUE',
 '142 MAUJER STREET',
 '146 MAUJER STREET',
 '152 MAUJER STREET',
 '243 GRAHAM AVENUE',
 '245 GRAHAM AVENUE',
 '247 GRAHAM AVENUE',
 '241 GRAHAM AVENUE',
 '147 TEN EYCK WALK',
 '235 GRAHAM AVENUE',
 '149 TEN EYCK WALK',
 '231 GRAHAM AVENUE',
 '233 GRAHAM AVENUE',
 '151 TEN EYCK WALK',
 '238 GRAHAM AVENUE',
 '161 TEN EYCK WALK',
 '240 GRAHAM AVENUE',
 '242 GRAHAM AVENUE',
 '244 GRAHAM AVENUE',
 '163 TEN EYCK WALK',
 '248 GRAHAM AVENUE',
 '246 GRAHAM AVENUE',
 '162 MAUJER STREET',
 '250 GRAHAM AVENUE',
 '252 GRAHAM AVENUE',
 '254 GRAHAM AVENUE',
 '160 MAUJER STREET',
 '164 MAUJER STREET',
 '165 TEN EYCK WALK',
 '167 TEN EYCK WALK',
 '169 TEN EYCK WALK',
 '2021 BOSTON ROAD',
 '1012 EAST 178TH STREET',
 '1030 EAST 178TH STREET',
 '1010 EAST 178TH STREET',
 '114 TAPSCOTT STREET',
 '104 TAPSCOTT STREET',
 '335 EAST 111TH STREET',
 '344 EAST 28TH STREET',
 '344GAR EAST 28TH STREET',
 '342 EAST 28TH STREET',
 '346 EAST 28TH STREET',
 '340 EAST 28TH STREET',
 '590 WARREN STREET',
 '572 WARREN STREET',
 '568 WARREN STREET',
 '565 BALTIC STREET',
 '574 WARREN STREET',
 '590 WARREN STREET -TEMPORARY ADDRESS',
 '513 GREENE AVENUE',
 '362 CLIFTON PLACE',
 '360 CLIFTON PLACE',
 '358 CLIFTON PLACE',
 '356 CLIFTON PLACE',
 '354 CLIFTON PLACE',
 '352 CLIFTON PLACE',
 '350 CLIFTON PLACE',
 '348 CLIFTON PLACE',
 '1909 AMSTERDAM AVENUE',
 '230 WEST 193RD STREET',
 '2663 HEATH AVENUE',
 '2661 HEATH AVENUE',
 '2667 HEATH AVENUE',
 '2660 BAILEY AVENUE',
 '1870 SCHIEFFELIN AVENUE',
 '1860 SCHIEFFELIN AVENUE',
 '1225 EAST 225TH STREET',
 '1871 SCHIEFFELIN PLACE',
 '1891 SCHIEFFELIN PLACE',
 '1220 EAST 229TH STREET',
 '1880 SCHIEFFELIN AVENUE',
 '1890 SCHIEFFELIN AVENUE',
 '1920 SCHIEFFELIN AVENUE',
 '1930 SCHIEFFELIN AVENUE',
 '1900 SCHIEFFELIN AVENUE',
 '1910 SCHIEFFELIN AVENUE',
 '1861 SCHIEFFELIN PLACE',
 '1881 SCHIEFFELIN PLACE',
 '1851 SCHIEFFELIN PLACE',
 '455 BARBEY STREET',
 '459 BARBEY STREET',
 '463 BARBEY STREET',
 '418 JEROME STREET',
 '422 JEROME STREET',
 '426 JEROME STREET',
 '610 BELMONT AVENUE',
 '616 BELMONT AVENUE',
 '100 SOUTH 10TH STREET',
 '447 BERRY STREET',
 '448 BERRY STREET',
 '449 BERRY STREET',
 '45 SOUTH 10TH STREET',
 '450 BERRY STREET',
 '451 BERRY STREET',
 '453 BERRY STREET',
 '455 BERRY STREET',
 '462 BEDFORD AVENUE',
 '464 BEDFORD AVENUE',
 '466 BEDFORD AVENUE',
 '49 SOUTH 10TH STREET',
 '51 SOUTH 10TH STREET',
 '53 SOUTH 10TH STREET',
 '55 SOUTH 10TH STREET',
 '57 SOUTH 10TH STREET',
 '59 SOUTH 10TH STREET',
 '61 SOUTH 10TH STREET',
 '63 SOUTH 10TH STREET',
 '65 SOUTH 10TH STREET',
 '67 SOUTH 10TH STREET',
 '74 SOUTH 9TH STREET',
 '65A SOUTH 10TH STREET',
 '440 BERRY STREET',
 '71 SOUTH 10TH STREET',
 '46 SOUTH 9TH STREET',
 '50 SOUTH 9TH STREET',
 '54 SOUTH 9TH STREET',
 '58 SOUTH 9TH STREET',
 '46 SOUTH 10TH STREET',
 '48 SOUTH 10TH STREET',
 '52 SOUTH 10TH STREET',
 '56 SOUTH 10TH STREET',
 '60 SOUTH 10TH STREET',
 '64 SOUTH 10TH STREET',
 '84 SOUTH 10TH STREET',
 '88 SOUTH 10TH STREET',
 '92 SOUTH 10TH STREET',
 '404 BROOK AVENUE',
 '510 EAST 144TH STREET',
 '400 BROOK AVENUE',
 '550 EAST 144TH STREET',
 '540 EAST 144TH STREET',
 '530 EAST 144TH STREET',
 '520 EAST 144TH STREET',
 '511 EAST 143RD STREET',
 '515 EAST 143RD STREET',
 '525 EAST 143RD STREET',
 '531 EAST 143RD STREET',
 '535 EAST 143RD STREET',
 '545 EAST 143RD STREET',
 '551 EAST 143RD STREET',
 '555 EAST 143RD STREET',
 '401 SAINT ANNS AVENUE',
 '560 EAST 144TH STREET',
 '700 EAST 140TH STREET',
 '690 EAST 140TH STREET',
 '443 EAST 137TH STREET',
 '453 EAST 137TH STREET',
 '455 EAST 137TH STREET',
 '463 EAST 137TH STREET',
 '408 EAST 137TH STREET',
 '416 EAST 137TH STREET',
 '505 EAST 144TH STREET',
 '509 EAST 144TH STREET',
 '511 EAST 144TH STREET',
 '517 EAST 144TH STREET',
 '695 EAST 139TH STREET',
 '451 EAST 136TH STREET',
 '411 EAST 136TH STREET',
 '427 SAINT ANNS AVENUE',
 '423 SAINT ANNS AVENUE',
 '480 EAST 143RD STREET',
 '490 EAST 143RD STREET',
 '433 EAST 146TH STREET',
 '435 EAST 146TH STREET',
 '437 EAST 146TH STREET',
 '439 EAST 146TH STREET',
 '441 EAST 146TH STREET',
 '513 EAST 146TH STREET',
 '511 EAST 146TH STREET',
 '417 EAST 146TH STREET',
 '419 EAST 146TH STREET',
 '421 EAST 146TH STREET',
 '423 EAST 146TH STREET',
 '425 EAST 146TH STREET',
 '427 EAST 146TH STREET',
 '429 EAST 146TH STREET',
 '431 EAST 146TH STREET',
 '527 EAST 146TH STREET',
 '545 EAST 146TH STREET',
 '547 EAST 146TH STREET',
 '537 EAST 146TH STREET',
 '512 EAST 146TH STREET',
 '510 EAST 146TH STREET',
 '530 EAST 146TH STREET',
 '528 EAST 146TH STREET',
 '455 EAST 146TH STREET',
 '450 EAST 143RD STREET',
 '521 EAST 146TH STREET',
 '525 EAST 146TH STREET',
 '521 EAST 145TH STREET',
 '525 EAST 145TH STREET',
 '400 EAST 147TH STREET',
 '460 EAST 147TH STREET',
 '550 EAST 147TH STREET',
 '474 WILLIS AVENUE',
 '465 SAINT ANNS AVENUE',
 '1943 AMSTERDAM AVENUE',
 '1945 AMSTERDAM AVENUE',
 '1949 AMSTERDAM AVENUE',
 '1947 AMSTERDAM AVENUE',
 '2440 BOSTON ROAD',
 '2430 BOSTON ROAD',
 '2424 BOSTON ROAD',
 '3475 BIVONA STREET',
 '3485 BIVONA STREET',
 '3555 BIVONA STREET',
 '3545 BIVONA STREET',
 '3565 BIVONA STREET',
 '3560 BIVONA STREET',
 '3550 BIVONA STREET',
 '3540 BIVONA STREET',
 '3580 BIVONA STREET',
 '3570 BIVONA STREET',
 '2185 REEDS MILL LANE',

In [32]:
merged_df['new_address'] = merged_df['og_address']

In [33]:
address_corrections = {'590 WARREN STREET -TEMPORARY ADDRESS':'590 WARREN STREET',
                       '1149GAR 229TH DRIVE NORTH':'1149 229TH DRIVE NORTH',
                       '2185GAR REEDS MILL LANE':'2185 REEDS MILL LANE',
                       '778GAR HENDERSON AVENUE':'778 HENDERSON AVENUE',
                       '344GAR EAST 28TH STREET':'344 EAST 28TH STREET',
                       'A C POWELL BOULEVARD':'ADAM C POWELL BOULEVARD',
                       '48REAR GRAFTON STREET':'48 GRAFTON STREET',
                       '365 FORD STREET, WING A':'365 FORD STREET',
                       '365 FORD STREET, WING B':'365 FORD STREET',
                       '365 FORD STREET, WING C':'365 FORD STREET',
                       '365 FORD STREET, WING D':'365 FORD STREET',
                       '365 EAST 183RD STREET, WING D':'365 EAST 183RD STREET',
                       '365 EAST 183RD STREET, WING E':'365 EAST 183RD STREET',
                       '365 EAST 183RD STREET, WING F':'365 EAST 183RD STREET'}

In [34]:
## iterate through and make replacements
for old_add, new_add in address_corrections.items():
    merged_df['new_address'] = merged_df['new_address'].str.replace(old_add,new_add)

In [35]:
# cleaning up the names of the street addresses so that they match the HPD data
merged_df['new_address'] = merged_df['new_address'].str.replace(r'(\d+)(ST|ND|TH|RD)\b', r'\1', regex=True)

In [36]:
merged_df.dev_name.nunique()

101

In [37]:
merged_df.dev_name.unique()

array(['ARMSTRONG I', 'ARMSTRONG II', 'BERRY STREET-SOUTH 9TH STREET',
       'BETANCES III, 13', 'BETANCES IV', 'BETANCES V', 'BOULEVARD',
       'BUSHWICK II (GROUPS A & C)', 'BUSHWICK II CDA (GROUP E)',
       'CROWN HEIGHTS', 'EASTCHESTER GARDENS', 'EDENWALD',
       'FENIMORE-LEFFERTS', 'FRANKLIN AVENUE II CONVENTIONAL',
       'HARLEM RIVER', 'HOWARD AVENUE', 'HOWARD AVENUE-PARK PLACE',
       'LINDEN', 'OCEAN BAY APARTMENTS (BAYSIDE)', 'PARK ROCK REHAB',
       'SAMUEL (CITY)', 'SOUTH BRONX AREA (SITE 402)',
       'TWIN PARKS WEST (SITES 1 & 2)', 'WEEKSVILLE GARDENS',
       'WILLIAMS PLAZA', 'WILLIAMSBURG', '1010 EAST 178TH STREET',
       '104-14 TAPSCOTT STREET', '335 EAST 111TH STREET',
       '344 EAST 28TH STREET', '572 WARREN STREET', 'AUDUBON',
       'BAILEY AVENUE-WEST 193RD STREET', 'BAYCHESTER',
       'BELMONT-SUTTER AREA', 'BETANCES I', 'BETANCES II, 13',
       'BETANCES II, 18', 'BETANCES III, 18', 'BETANCES II, 9A',
       'BETANCES III, 9A', 'BETANCES VI', 'BETHUNE GARDENS',
       'BOSTON ROAD PLAZA', 'BOSTON SECOR', 'BUSHWICK II (GROUPS B & D)',
       'CLAREMONT PARKWAY-FRANKLIN AVENUE', 'DAVIDSON',
       'EAGLE AVENUE-EAST 163RD STREET',
       'EAST 180TH STREET-MONTEREY AVENUE', 'FIORENTINO PLAZA',
       'FORT INDEPENDENCE STREET-HEATH AVENUE',
       'FORT WASHINGTON AVENUE REHAB', 'FRANKLIN AVENUE I CONVENTIONAL',
       'FRANKLIN AVENUE III CONVENTIONAL', 'GRAMPION', 'HARLEM RIVER II',
       'HARRISON AVENUE REHAB (GROUP A)',
       'HARRISON AVENUE REHAB (GROUP B)',
       'HIGHBRIDGE REHABS (ANDERSON AVENUE)',
       'HIGHBRIDGE REHABS (NELSON AVENUE)', 'HOPE GARDENS',
       'INDEPENDENCE', 'LENOX ROAD-ROCKAWAY PARKWAY', 'MANHATTANVILLE',
       'MANHATTANVILLE REHAB (GROUP 2)', 'MANHATTANVILLE REHAB (GROUP 3)',
       'MARCY AVENUE-GREENE AVENUE SITE A',
       'MARCY AVENUE-GREENE AVENUE SITE B', 'MARSHALL PLAZA',
       'MIDDLETOWN PLAZA', 'MURPHY', 'OCEAN HILL-BROWNSVILLE',
       'PALMETTO GARDENS', 'PARK AVENUE-EAST 122ND, 123RD STREETS',
       'PENNSYLVANIA AVENUE-WORTMAN AVENUE',
       'PUBLIC SCHOOL 139 (CONVERSION)', 'RALPH AVENUE REHAB',
       'REID APARTMENTS', 'RUTLAND TOWERS', 'SACK WERN',
       'SAMUEL (MHOP) I', 'SAMUEL (MHOP) II', 'SAMUEL (MHOP) III',
       'STEBBINS AVENUE-HEWITT PLACE',
       'STERLING PLACE REHABS (SAINT JOHNS-STERLING)',
       'STERLING PLACE REHABS (STERLING-BUFFALO)',
       'SUTTER AVENUE-UNION STREET', 'TAPSCOTT STREET REHAB',
       'TWIN PARKS EAST (SITE 9)', 'UNION AVENUE-EAST 163RD STREET',
       'UNION AVENUE-EAST 166TH STREET', 'UNIVERSITY AVENUE REHAB',
       'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
       'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
       'WASHINGTON HEIGHTS REHAB PHASE III (HARLEM RIVER)',
       'WASHINGTON HEIGHTS REHAB PHASE IV (C)',
       'WASHINGTON HEIGHTS REHAB PHASE IV (D)', 'WEST BRIGHTON I',
       'WEST BRIGHTON II', 'WISE TOWERS'], dtype=object)

In [38]:
print(f'number of unique addresses from old column:{merged_df.og_address.nunique()}\nnumber of unique address from new column:{merged_df.new_address.nunique()}')

number of unique addresses from old column:1538
number of unique address from new column:1526

In [39]:
## drop
dropped_df = merged_df.drop_duplicates(subset=['new_address','bin','bbl'],keep='first')

In [40]:
## check again
print(f'number of unique address: {dropped_df.new_address.nunique()} \nnumber of unique bins: {dropped_df.bin.nunique()}\nnumber of unique developments:{dropped_df.dev_name.nunique()}')

number of unique address: 1526
number of unique bins: 715
number of unique developments:101

In [41]:
dropped_df.dev_name.unique().tolist()

['ARMSTRONG I',
 'ARMSTRONG II',
 'BERRY STREET-SOUTH 9TH STREET',
 'BETANCES III, 13',
 'BETANCES IV',
 'BOULEVARD',
 'BUSHWICK II (GROUPS A & C)',
 'BUSHWICK II CDA (GROUP E)',
 'CROWN HEIGHTS',
 'EASTCHESTER GARDENS',
 'EDENWALD',
 'FENIMORE-LEFFERTS',
 'FRANKLIN AVENUE II CONVENTIONAL',
 'HARLEM RIVER',
 'HOWARD AVENUE',
 'HOWARD AVENUE-PARK PLACE',
 'LINDEN',
 'OCEAN BAY APARTMENTS (BAYSIDE)',
 'PARK ROCK REHAB',
 'SAMUEL (CITY)',
 'SOUTH BRONX AREA (SITE 402)',
 'TWIN PARKS WEST (SITES 1 & 2)',
 'WEEKSVILLE GARDENS',
 'WILLIAMS PLAZA',
 'WILLIAMSBURG',
 '1010 EAST 178TH STREET',
 '104-14 TAPSCOTT STREET',
 '335 EAST 111TH STREET',
 '344 EAST 28TH STREET',
 '572 WARREN STREET',
 'AUDUBON',
 'BAILEY AVENUE-WEST 193RD STREET',
 'BAYCHESTER',
 'BELMONT-SUTTER AREA',
 'BETANCES I',
 'BETANCES II, 13',
 'BETANCES II, 18',
 'BETANCES II, 9A',
 'BETANCES III, 18',
 'BETANCES III, 9A',
 'BETANCES V',
 'BETANCES VI',
 'BETHUNE GARDENS',
 'BOSTON ROAD PLAZA',
 'BOSTON SECOR',
 'BUSHWICK II (GROUPS B & D)',
 'CLAREMONT PARKWAY-FRANKLIN AVENUE',
 'DAVIDSON',
 'EAGLE AVENUE-EAST 163RD STREET',
 'EAST 180TH STREET-MONTEREY AVENUE',
 'FIORENTINO PLAZA',
 'FORT INDEPENDENCE STREET-HEATH AVENUE',
 'FORT WASHINGTON AVENUE REHAB',
 'FRANKLIN AVENUE I CONVENTIONAL',
 'FRANKLIN AVENUE III CONVENTIONAL',
 'GRAMPION',
 'HARLEM RIVER II',
 'HARRISON AVENUE REHAB (GROUP A)',
 'HARRISON AVENUE REHAB (GROUP B)',
 'HIGHBRIDGE REHABS (ANDERSON AVENUE)',
 'HIGHBRIDGE REHABS (NELSON AVENUE)',
 'HOPE GARDENS',
 'INDEPENDENCE',
 'LENOX ROAD-ROCKAWAY PARKWAY',
 'MANHATTANVILLE',
 'MANHATTANVILLE REHAB (GROUP 2)',
 'MANHATTANVILLE REHAB (GROUP 3)',
 'MARCY AVENUE-GREENE AVENUE SITE A',
 'MARCY AVENUE-GREENE AVENUE SITE B',
 'MARSHALL PLAZA',
 'MIDDLETOWN PLAZA',
 'MURPHY',
 'OCEAN HILL-BROWNSVILLE',
 'PALMETTO GARDENS',
 'PARK AVENUE-EAST 122ND, 123RD STREETS',
 'PENNSYLVANIA AVENUE-WORTMAN AVENUE',
 'PUBLIC SCHOOL 139 (CONVERSION)',
 'RALPH AVENUE REHAB',
 'REID APARTMENTS',
 'RUTLAND TOWERS',
 'SACK WERN',
 'SAMUEL (MHOP) I',
 'SAMUEL (MHOP) II',
 'SAMUEL (MHOP) III',
 'STEBBINS AVENUE-HEWITT PLACE',
 'STERLING PLACE REHABS (SAINT JOHNS-STERLING)',
 'STERLING PLACE REHABS (STERLING-BUFFALO)',
 'SUTTER AVENUE-UNION STREET',
 'TAPSCOTT STREET REHAB',
 'TWIN PARKS EAST (SITE 9)',
 'UNION AVENUE-EAST 163RD STREET',
 'UNION AVENUE-EAST 166TH STREET',
 'UNIVERSITY AVENUE REHAB',
 'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
 'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
 'WASHINGTON HEIGHTS REHAB PHASE III (HARLEM RIVER)',
 'WASHINGTON HEIGHTS REHAB PHASE IV (C)',
 'WASHINGTON HEIGHTS REHAB PHASE IV (D)',
 'WEST BRIGHTON I',
 'WEST BRIGHTON II',
 'WISE TOWERS']

In [42]:
test = dropped_df[dropped_df['dev_name'] == 'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)']
test.head()

,bbl,bldg,m,og_address,zip code,cd,fc,ss,sa,cc,bin,dev_name,boro,units,transfer,new_address
19976,1021320047,1,M,501 WEST 176TH STREET,10033,12,13,31,72,10,1063193,WASHINGTON HEIGHTS REHAB (GROUPS 1&2),manhattan,216,11/30/2020,501 WEST 176 STREET
19980,1021320047,1,,2340 AMSTERDAM AVENUE,10033,12,13,31,72,10,1063193,WASHINGTON HEIGHTS REHAB (GROUPS 1&2),manhattan,216,11/30/2020,2340 AMSTERDAM AVENUE
19984,1021320047,1,,2346 AMSTERDAM AVENUE,10033,12,13,31,72,10,1063193,WASHINGTON HEIGHTS REHAB (GROUPS 1&2),manhattan,216,11/30/2020,2346 AMSTERDAM AVENUE
19988,1021320047,1,M,500 WEST 177TH STREET,10033,12,13,31,72,10,1063193,WASHINGTON HEIGHTS REHAB (GROUPS 1&2),manhattan,216,11/30/2020,500 WEST 177 STREET
19992,1021320110,2,M,503 WEST 177TH STREET,10033,12,13,31,72,10,1063213,WASHINGTON HEIGHTS REHAB (GROUPS 1&2),manhattan,216,11/30/2020,503 WEST 177 STREET

In [43]:
dropped_df.dev_name.unique().tolist()

['ARMSTRONG I',
 'ARMSTRONG II',
 'BERRY STREET-SOUTH 9TH STREET',
 'BETANCES III, 13',
 'BETANCES IV',
 'BOULEVARD',
 'BUSHWICK II (GROUPS A & C)',
 'BUSHWICK II CDA (GROUP E)',
 'CROWN HEIGHTS',
 'EASTCHESTER GARDENS',
 'EDENWALD',
 'FENIMORE-LEFFERTS',
 'FRANKLIN AVENUE II CONVENTIONAL',
 'HARLEM RIVER',
 'HOWARD AVENUE',
 'HOWARD AVENUE-PARK PLACE',
 'LINDEN',
 'OCEAN BAY APARTMENTS (BAYSIDE)',
 'PARK ROCK REHAB',
 'SAMUEL (CITY)',
 'SOUTH BRONX AREA (SITE 402)',
 'TWIN PARKS WEST (SITES 1 & 2)',
 'WEEKSVILLE GARDENS',
 'WILLIAMS PLAZA',
 'WILLIAMSBURG',
 '1010 EAST 178TH STREET',
 '104-14 TAPSCOTT STREET',
 '335 EAST 111TH STREET',
 '344 EAST 28TH STREET',
 '572 WARREN STREET',
 'AUDUBON',
 'BAILEY AVENUE-WEST 193RD STREET',
 'BAYCHESTER',
 'BELMONT-SUTTER AREA',
 'BETANCES I',
 'BETANCES II, 13',
 'BETANCES II, 18',
 'BETANCES II, 9A',
 'BETANCES III, 18',
 'BETANCES III, 9A',
 'BETANCES V',
 'BETANCES VI',
 'BETHUNE GARDENS',
 'BOSTON ROAD PLAZA',
 'BOSTON SECOR',
 'BUSHWICK II (GROUPS B & D)',
 'CLAREMONT PARKWAY-FRANKLIN AVENUE',
 'DAVIDSON',
 'EAGLE AVENUE-EAST 163RD STREET',
 'EAST 180TH STREET-MONTEREY AVENUE',
 'FIORENTINO PLAZA',
 'FORT INDEPENDENCE STREET-HEATH AVENUE',
 'FORT WASHINGTON AVENUE REHAB',
 'FRANKLIN AVENUE I CONVENTIONAL',
 'FRANKLIN AVENUE III CONVENTIONAL',
 'GRAMPION',
 'HARLEM RIVER II',
 'HARRISON AVENUE REHAB (GROUP A)',
 'HARRISON AVENUE REHAB (GROUP B)',
 'HIGHBRIDGE REHABS (ANDERSON AVENUE)',
 'HIGHBRIDGE REHABS (NELSON AVENUE)',
 'HOPE GARDENS',
 'INDEPENDENCE',
 'LENOX ROAD-ROCKAWAY PARKWAY',
 'MANHATTANVILLE',
 'MANHATTANVILLE REHAB (GROUP 2)',
 'MANHATTANVILLE REHAB (GROUP 3)',
 'MARCY AVENUE-GREENE AVENUE SITE A',
 'MARCY AVENUE-GREENE AVENUE SITE B',
 'MARSHALL PLAZA',
 'MIDDLETOWN PLAZA',
 'MURPHY',
 'OCEAN HILL-BROWNSVILLE',
 'PALMETTO GARDENS',
 'PARK AVENUE-EAST 122ND, 123RD STREETS',
 'PENNSYLVANIA AVENUE-WORTMAN AVENUE',
 'PUBLIC SCHOOL 139 (CONVERSION)',
 'RALPH AVENUE REHAB',
 'REID APARTMENTS',
 'RUTLAND TOWERS',
 'SACK WERN',
 'SAMUEL (MHOP) I',
 'SAMUEL (MHOP) II',
 'SAMUEL (MHOP) III',
 'STEBBINS AVENUE-HEWITT PLACE',
 'STERLING PLACE REHABS (SAINT JOHNS-STERLING)',
 'STERLING PLACE REHABS (STERLING-BUFFALO)',
 'SUTTER AVENUE-UNION STREET',
 'TAPSCOTT STREET REHAB',
 'TWIN PARKS EAST (SITE 9)',
 'UNION AVENUE-EAST 163RD STREET',
 'UNION AVENUE-EAST 166TH STREET',
 'UNIVERSITY AVENUE REHAB',
 'WASHINGTON HEIGHTS REHAB (GROUPS 1&2)',
 'WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHINGTON)',
 'WASHINGTON HEIGHTS REHAB PHASE III (HARLEM RIVER)',
 'WASHINGTON HEIGHTS REHAB PHASE IV (C)',
 'WASHINGTON HEIGHTS REHAB PHASE IV (D)',
 'WEST BRIGHTON I',
 'WEST BRIGHTON II',
 'WISE TOWERS']

In [44]:
dropped_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1531 entries, 0 to 23061
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   bbl          1531 non-null   object
 1   bldg         1531 non-null   object
 2   m            1531 non-null   object
 3   og_address   1531 non-null   object
 4   zip code     1531 non-null   object
 5   cd           1531 non-null   object
 6   fc           1531 non-null   object
 7   ss           1531 non-null   object
 8   sa           1531 non-null   object
 9   cc           1531 non-null   object
 10  bin          1531 non-null   object
 11  dev_name     1531 non-null   object
 12  boro         1508 non-null   object
 13  units        1508 non-null   object
 14  transfer     1508 non-null   object
 15  new_address  1531 non-null   object
dtypes: object(16)
memory usage: 203.3+ KB

In [45]:
## write to a csv
dropped_df.to_csv('../input/coded_files/addresses_updated_120525.csv',index=False)