## Import Libraries and Data

[NYC Department of Housing Preservation and Development Open Market Orders Charges](https://data.cityofnewyork.us/Housing-Development/Open-Market-Order-OMO-Charges/mdbu-nrqn/about_data)

[NYC Department of Housing Preservation and Development Housing Maintenance Code Violations](https://data.cityofnewyork.us/Housing-Development/Housing-Maintenance-Code-Violations/wvxf-dwi5/about_data)

In [1]:
## import libraries
import pandas as pd
import numpy as np

In [2]:
## import data
omo_df = pd.read_csv('../input/Open_Market_Order_(OMO)_Charges_20251202.csv', dtype = {'OMOID':'object',
                                                                                       'BIN':'object',
                                                                                       'OMONumber':'object',
                                                                                       'BuildingID':'object',
                                                                                       'Boro ID':'object',
                                                                                       'BBL':'object',
                                                                                       'Block':'object',
                                                                                       'Lot':'object',
                                                                                       'HouseNumber':'object',
                                                                                       'Zip':'object',
                                                                                       'IsAEP':'object',
                                                                                       'IsCommercialDemolition':'object',
                                                                                       'FEMAEvent':'object',
                                                                                       'FEMAEvenID':'object'})

/var/folders/t4/yhv9cps51w7bfdt0w1lkv1zm0000gn/T/ipykernel_28281/2616853611.py:2: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  omo_df = pd.read_csv('../input/Open_Market_Order_(OMO)_Charges_20251202.csv', dtype = {'OMOID':'object',

In [3]:
omo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494233 entries, 0 to 494232
Data columns (total 32 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   OMOID                   494233 non-null  object
 1   OMONumber               494233 non-null  object
 2   BuildingID              494233 non-null  object
 3   Boro ID                 494233 non-null  object
 4   Boro                    494233 non-null  object
 5   HouseNumber             494233 non-null  object
 6   StreetName              494233 non-null  object
 7   Apartment               371362 non-null  object
 8   Zip                     494002 non-null  object
 9   Block                   494233 non-null  object
 10  Lot                     494233 non-null  object
 11  LifeCycle               494233 non-null  object
 12  WorkTypeGeneral         494233 non-null  object
 13  OMOStatusReason         485854 non-null  object
 14  OMOAwardAmount          494233 non-null  object
 15  OMOCreateDate           494233 non-null  object
 16  NetChangeOrders         494233 non-null  int64
 17  OMOAwardDate            475181 non-null  object
 18  IsAEP                   34316 non-null   object
 19  IsCommercialDemolition  1006 non-null    object
 20  ServiceChargeFlag       494233 non-null  bool
 21  FEMAEventID             1287 non-null    object
 22  FEMAEvent               1118 non-null    object
 23  OMODescription          494222 non-null  object
 24  Latitude                493890 non-null  float64
 25  Longitude               493890 non-null  float64
 26  Community Board         493890 non-null  float64
 27  Council District        493890 non-null  float64
 28  Census Tract            493890 non-null  float64
 29  BIN                     493151 non-null  object
 30  BBL                     493151 non-null  object
 31  NTA                     493890 non-null  object
dtypes: bool(1), float64(5), int64(1), object(25)
memory usage: 117.4+ MB

In [16]:
omo_df.omocreatedate.unique().tolist()

['08/08/2023',
 '08/07/2020',
 '07/07/2022',
 '07/09/2020',
 '07/25/2022',
 '09/27/2023',
 '11/03/2020',
 '09/28/2023',
 '05/05/2020',
 '12/08/2022',
 '10/09/2023',
 '03/26/2020',
 '10/18/2023',
 '10/16/2023',
 '10/13/2023',
 '03/29/2022',
 '10/25/2023',
 '07/24/2020',
 '04/13/2022',
 '07/23/2019',
 '07/26/2020',
 '07/27/2020',
 '10/19/2023',
 '04/21/2022',
 '10/22/2020',
 '12/06/2022',
 '10/26/2023',
 '06/09/2020',
 '07/28/2020',
 '11/16/2020',
 '05/18/2021',
 '07/13/2021',
 '02/02/2024',
 '07/29/2020',
 '11/22/2010',
 '08/31/2021',
 '10/27/2023',
 '04/19/2022',
 '08/25/2021',
 '09/01/2023',
 '09/18/2023',
 '07/21/2021',
 '10/28/2023',
 '05/16/2022',
 '07/12/2022',
 '05/12/2023',
 '05/02/2023',
 '11/22/2024',
 '09/19/2022',
 '08/03/2020',
 '04/20/2023',
 '11/15/2021',
 '10/04/2022',
 '02/15/2022',
 '10/10/2023',
 '10/30/2023',
 '11/22/2022',
 '05/09/2022',
 '09/17/2021',
 '10/12/2023',
 '03/10/2020',
 '08/05/2021',
 '01/05/2022',
 '08/04/2020',
 '05/12/2022',
 '01/07/2022',
 '08/18/2022',
 '04/29/2022',
 '12/08/2023',
 '11/29/2022',
 '01/20/2022',
 '03/29/2021',
 '04/10/2021',
 '04/27/2021',
 '05/05/2021',
 '10/10/2021',
 '07/20/2023',
 '08/05/2020',
 '07/19/2023',
 '05/19/2022',
 '09/27/2022',
 '12/27/2023',
 '12/21/2022',
 '01/02/2024',
 '07/19/2022',
 '07/21/2022',
 '07/26/2022',
 '08/12/2022',
 '08/16/2022',
 '02/24/2022',
 '01/11/2023',
 '01/05/2024',
 '08/06/2020',
 '08/23/2022',
 '08/24/2022',
 '07/01/2022',
 '07/22/2023',
 '07/21/2023',
 '03/10/2022',
 '01/08/2024',
 '05/01/2024',
 '03/18/2022',
 '10/18/2021',
 '06/09/2022',
 '03/25/2022',
 '02/02/2022',
 '09/02/2022',
 '06/15/2022',
 '07/14/2021',
 '06/16/2022',
 '07/13/2022',
 '07/25/2023',
 '06/11/2022',
 '01/24/2022',
 '02/03/2022',
 '08/07/2019',
 '02/20/2021',
 '09/07/2022',
 '03/30/2022',
 '01/25/2023',
 '08/08/2020',
 '07/11/2021',
 '07/18/2022',
 '03/31/2022',
 '07/29/2021',
 '09/08/2022',
 '06/24/2022',
 '12/07/2022',
 '06/23/2022',
 '08/10/2020',
 '04/04/2022',
 '10/20/2021',
 '11/16/2021',
 '12/12/2022',
 '04/14/2020',
 '04/30/2020',
 '04/29/2020',
 '01/27/2023',
 '06/27/2022',
 '04/06/2022',
 '07/18/2019',
 '01/29/2021',
 '06/29/2022',
 '02/13/2021',
 '06/28/2022',
 '09/14/2022',
 '02/22/2021',
 '09/21/2022',
 '11/22/2021',
 '03/07/2021',
 '12/20/2022',
 '07/27/2023',
 '03/08/2021',
 '07/27/2022',
 '06/30/2022',
 '03/10/2021',
 '03/12/2021',
 '10/26/2021',
 '04/09/2022',
 '02/27/2023',
 '03/01/2023',
 '03/16/2021',
 '11/23/2021',
 '07/05/2022',
 '02/28/2023',
 '02/25/2023',
 '11/30/2021',
 '01/12/2024',
 '03/17/2021',
 '03/18/2021',
 '03/20/2021',
 '04/11/2022',
 '07/06/2022',
 '03/19/2021',
 '04/12/2022',
 '03/03/2023',
 '12/15/2021',
 '08/02/2022',
 '03/23/2021',
 '08/16/2023',
 '03/25/2021',
 '01/13/2024',
 '09/15/2021',
 '07/28/2023',
 '08/04/2022',
 '01/06/2022',
 '03/26/2021',
 '01/10/2023',
 '07/29/2023',
 '10/28/2021',
 '03/08/2023',
 '03/30/2021',
 '02/14/2020',
 '12/22/2020',
 '01/23/2024',
 '10/11/2022',
 '07/11/2022',
 '01/16/2024',
 '01/18/2022',
 '07/10/2022',
 '01/19/2022',
 '10/12/2022',
 '06/02/2020',
 '10/13/2022',
 '03/16/2023',
 '01/21/2022',
 '06/03/2020',
 '03/31/2021',
 '07/31/2023',
 '08/19/2020',
 '10/18/2022',
 '10/29/2021',
 '10/17/2022',
 '12/24/2020',
 '10/21/2022',
 '02/25/2021',
 '02/24/2021',
 '03/20/2023',
 '01/25/2022',
 '01/16/2023',
 '08/04/2021',
 '10/24/2022',
 '04/01/2021',
 '11/29/2023',
 '01/27/2022',
 '11/06/2023',
 '11/01/2021',
 '01/26/2022',
 '08/14/2020',
 '03/23/2023',
 '08/06/2021',
 '04/02/2021',
 '01/18/2023',
 '01/17/2024',
 '03/24/2023',
 '01/31/2022',
 '01/29/2022',
 '08/09/2021',
 '02/21/2020',
 '01/19/2023',
 '04/03/2021',
 '11/17/2020',
 '08/02/2023',
 '10/29/2022',
 '07/14/2022',
 '02/01/2022',
 '11/24/2020',
 '03/14/2024',
 '11/02/2021',
 '11/02/2022',
 '04/03/2020',
 '03/22/2024',
 '04/05/2021',
 '03/30/2023',
 '07/10/2020',
 '01/18/2024',
 '07/17/2020',
 '07/15/2020',
 '07/16/2020',
 '11/03/2021',
 '07/20/2020',
 '04/01/2023',
 '04/06/2021',
 '04/03/2023',
 '12/09/2020',
 '12/08/2020',
 '04/04/2023',
 '09/15/2022',
 '04/05/2023',
 '04/07/2021',
 '11/10/2022',
 '07/31/2020',
 '04/06/2023',
 '10/02/2023',
 '07/30/2020',
 '04/10/2024',
 '12/11/2020',
 '12/10/2020',
 '07/16/2022',
 '11/14/2022',
 '04/08/2021',
 '01/19/2024',
 '11/04/2021',
 '04/07/2023',
 '12/12/2020',
 '08/03/2023',
 '01/23/2023',
 '12/14/2020',
 '04/08/2023',
 '11/15/2022',
 '04/10/2023',
 '09/20/2022',
 '10/03/2023',
 '11/16/2022',
 '04/16/2024',
 '01/20/2024',
 '11/05/2021',
 '04/11/2023',
 '04/17/2024',
 '01/22/2024',
 '11/17/2022',
 '11/18/2022',
 '02/07/2022',
 '08/07/2023',
 '08/18/2023',
 '11/19/2022',
 '04/12/2023',
 '11/21/2022',
 '07/26/2021',
 '04/20/2022',
 '04/13/2023',
 '12/17/2020',
 '04/19/2024',
 '08/11/2020',
 '02/08/2022',
 '07/23/2022',
 '08/17/2022',
 '09/22/2022',
 '04/14/2023',
 '06/22/2023',
 '04/22/2024',
 '08/21/2023',
 '06/04/2020',
 '06/05/2020',
 '04/15/2023',
 '11/23/2022',
 '04/17/2021',
 '04/19/2021',
 '06/07/2021',
 '01/24/2024',
 '01/25/2024',
 '04/17/2023',
 '10/20/2023',
 '03/08/2022',
 '01/26/2023',
 '03/23/2022',
 '04/18/2023',
 '07/28/2021',
 '04/02/2022',
 '05/04/2023',
 '05/11/2023',
 '03/29/2023',
 '05/24/2022',
 '04/24/2024',
 '04/26/2022',
 '11/25/2022',
 '09/23/2022',
 '05/15/2023',
 '11/26/2022',
 '05/19/2023',
 '03/01/2022',
 '06/27/2023',
 '02/17/2022',
 '11/28/2022',
 '05/06/2022',
 '05/17/2022',
 '10/31/2023',
 '04/12/2021',
 '05/06/2020',
 '03/24/2020',
 '03/03/2020',
 '04/18/2020',
 '09/04/2020',
 '09/23/2020',
 '01/26/2024',
 '09/26/2022',
 '05/21/2022',
 '11/09/2023',
 '07/25/2020',
 '02/17/2021',
 '01/29/2020',
 '03/03/2021',
 '06/21/2022',
 '08/03/2021',
 '01/30/2023',
 '05/03/2012',
 '04/16/2013',
 '10/02/2013',
 '01/30/2014',
 '04/25/2024',
 '08/27/2014',
 '03/22/2021',
 '03/08/2017',
 '03/21/2021',
 '11/10/2021',
 '03/24/2021',
 '05/07/2020',
 '02/12/2020',
 '01/31/2023',
 '12/04/2020',
 '12/07/2020',
 '05/08/2020',
 '08/16/2021',
 '05/18/2020',
 '07/26/2023',
 '05/16/2020',
 '03/28/2021',
 '02/02/2023',
 '11/03/2023',
 '02/22/2023',
 '11/19/2021',
 '11/15/2023',
 '02/14/2022',
 '07/08/2022',
 '12/15/2020',
 '11/26/2021',
 '07/09/2022',
 '05/09/2020',
 '03/06/2020',
 '12/16/2020',
 '12/03/2021',
 '12/08/2021',
 '08/12/2020',
 '06/06/2020',
 '12/10/2021',
 '04/26/2024',
 '03/28/2022',
 '12/13/2021',
 '11/07/2023',
 '04/04/2021',
 '04/24/2023',
 '04/01/2022',
 '01/31/2024',
 '10/10/2019',
 '01/10/2022',
 '04/05/2022',
 '01/13/2022',
 '04/27/2024',
 '01/15/2022',
 '02/18/2022',
 '05/11/2019',
 '05/29/2019',
 '04/07/2022',
 '01/22/2022',
 '03/18/2020',
 '02/07/2020',
 '08/17/2020',
 '06/30/2021',
 '02/05/2020',
 '02/06/2020',
 '11/18/2021',
 '02/13/2020',
 '02/10/2020',
 '12/16/2021',
 '02/20/2020',
 '04/29/2024',
 '02/25/2020',
 '12/28/2022',
 '12/02/2022',
 '08/18/2020',
 '02/26/2020',
 '12/23/2020',
 '03/02/2020',
 '11/06/2020',
 '10/30/2020',
 '01/28/2022',
 '07/15/2021',
 '04/09/2021',
 '07/18/2021',
 '08/21/2020',
 '03/27/2020',
 '07/22/2021',
 '08/24/2020',
 '04/07/2020',
 '04/13/2020',
 '04/23/2020',
 '04/21/2020',
 '04/24/2020',
 '08/22/2023',
 '09/30/2022',
 '05/04/2020',
 '12/05/2022',
 '11/16/2023',
 '05/14/2020',
 '08/13/2020',
 '08/17/2018',
 '07/30/2019',
 '05/19/2020',
 '08/06/2019',
 '06/24/2019',
 '12/28/2020',
 '05/20/2020',
 '04/13/2021',
 '05/21/2020',
 '02/04/2022',
 '07/18/2020',
 '10/28/2020',
 '04/30/2024',
 '01/30/2024',
 '10/01/2022',
 '04/28/2023',
 '02/23/2022',
 '04/20/2020',
 '04/29/2023',
 '08/05/2023',
 '11/22/2020',
 '03/25/2020',
 '03/23/2020',
 '08/28/2023',
 '08/23/2023',
 '10/22/2021',
 '11/25/2020',
 '05/27/2020',
 '11/21/2023',
 '12/02/2020',
 '04/10/2020',
 '07/22/2022',
 '12/05/2020',
 '02/19/2020',
 '02/11/2020',
 '08/09/2020',
 '06/22/2021',
 '04/16/2021',
 '07/01/2023',
 '09/20/2023',
 '09/12/2023',
 '10/24/2023',
 '11/28/2023',
 '11/30/2023',
 '10/07/2023',
 '12/26/2023',
 '08/02/2021',
 '12/15/2023',
 '08/04/2023',
 '01/09/2024',
 '01/06/2024',
 '04/16/2020',
 '04/21/2023',
 '03/09/2022',
 '03/22/2022',
 '02/01/2023',
 '04/21/2021',
 '01/11/2024',
 '04/20/2021',
 '01/10/2024',
 '01/16/2021',
 '07/18/2023',
 '07/14/2023',
 '07/17/2023',
 '05/12/2020',
 '04/25/2022',
 '04/28/2022',
 '12/21/2021',
 '03/24/2022',
 '06/07/2022',
 '08/01/2022',
 '05/18/2022',
 '01/15/2024',
 '11/22/2023',
 '07/15/2022',
 '08/25/2022',
 '07/24/2023',
 '07/06/2023',
 '09/06/2024',
 '09/13/2022',
 '11/25/2023',
 '09/16/2022',
 '03/13/2020',
 '03/14/2020',
 '04/22/2021',
 '08/25/2020',
 '03/12/2020',
 '11/27/2023',
 '08/07/2021',
 '05/29/2020',
 '08/15/2020',
 '08/22/2020',
 '09/29/2022',
 '03/19/2020',
 '10/15/2020',
 '12/30/2020',
 '12/29/2020',
 '08/27/2019',
 '08/11/2021',
 '08/10/2021',
 '03/20/2020',
 '10/06/2022',
 '03/10/2023',
 '12/26/2020',
 '02/16/2021',
 '07/21/2020',
 '04/27/2022',
 '02/18/2021',
 '02/26/2021',
 '02/28/2021',
 '09/17/2020',
 '05/28/2020',
 '05/26/2020',
 '09/22/2020',
 '10/20/2020',
 '04/03/2019',
 '10/13/2020',
 '06/06/2019',
 '03/15/2021',
 '11/01/2020',
 '01/31/2020',
 '02/04/2020',
 '11/08/2020',
 '11/09/2020',
 '05/07/2024',
 '02/17/2020',
 '08/01/2023',
 '10/26/2022',
 '02/18/2020',
 '03/30/2020',
 '12/01/2023',
 '03/31/2020',
 '04/02/2020',
 '04/01/2020',
 '03/04/2020',
 '04/06/2020',
 '11/21/2020',
 '03/16/2020',
 '03/09/2020',
 '03/17/2020',
 '12/20/2021',
 '01/04/2022',
 '11/01/2022',
 '04/08/2020',
 '10/30/2022',
 '12/07/2023',
 '11/04/2022',
 '02/12/2024',
 '11/05/2022',
 '11/08/2022',
 '02/15/2024',
 '12/03/2020',
 '07/02/2021',
 '05/13/2020',
 '02/28/2024',
 '02/29/2024',
 '05/15/2020',
 '11/08/2023',
 '11/13/2022',
 '03/20/2024',
 '03/18/2024',
 '03/11/2024',
 '02/25/2019',
 '04/02/2024',
 '11/29/2021',
 '11/27/2021',
 '01/30/2020',
 '10/05/2022',
 '01/27/2024',
 '11/07/2022',
 '06/08/2020',
 '01/29/2024',
 '08/30/2023',
 '12/15/2022',
 '08/09/2023',
 '01/23/2022',
 '04/14/2022',
 '07/28/2022',
 '04/18/2024',
 '11/16/2024',
 '01/05/2023',
 '08/26/2020',
 '12/21/2020',
 '04/19/2023',
 '04/15/2022',
 '04/23/2024',
 '01/14/2023',
 '10/11/2023',
 '08/22/2019',
 '09/17/2019',
 '03/14/2023',
 '10/14/2023',
 '11/30/2022',
 '06/14/2020',
 '06/15/2020',
 '04/15/2021',
 '06/16/2020',
 '05/25/2022',
 '02/05/2024',
 '06/02/2022',
 '06/17/2022',
 '01/20/2023',
 '07/12/2023',
 '12/01/2022',
 '12/10/2019',
 '07/15/2019',
 '08/31/2020',
 '02/01/2024',
 '07/06/2021',
 '08/10/2023',
 '08/17/2021',
 '11/13/2020',
 '08/14/2023',
 '11/20/2020',
 '11/20/2023',
 '09/21/2021',
 '09/27/2021',
 '06/08/2021',
 '04/26/2023',
 '11/26/2020',
 '10/06/2021',
 '10/13/2021',
 '10/14/2021',
 '10/19/2021',
 '04/23/2021',
 '11/04/2023',
 '10/21/2021',
 '03/02/2022',
 '10/24/2021',
 '01/14/2021',
 '10/27/2021',
 '04/15/2020',
 '03/02/2021',
 '03/06/2021',
 '12/19/2020',
 '03/14/2021',
 '08/27/2020',
 '05/03/2023',
 '10/30/2021',
 '10/31/2021',
 '03/07/2022',
 '05/02/2024',
 '05/02/2019',
 '11/14/2020',
 '11/09/2021',
 '03/05/2020',
 '12/14/2022',
 '06/03/2022',
 '06/04/2022',
 '02/03/2023',
 '06/08/2022',
 '07/02/2022',
 '05/22/2020',
 '12/07/2021',
 '02/06/2023',
 '11/08/2021',
 '08/09/2022',
 '08/10/2022',
 '01/24/2023',
 '03/04/2023',
 '07/29/2022',
 '08/20/2020',
 '04/14/2021',
 '12/09/2022',
 '06/11/2020',
 '08/15/2022',
 '12/19/2022',
 '07/30/2023',
 '08/29/2022',
 '11/01/2023',
 '01/06/2023',
 '09/06/2022',
 '02/19/2024',
 '02/16/2024',
 '10/27/2022',
 '09/09/2022',
 '03/05/2024',
 '09/12/2022',
 '03/07/2024',
 '03/13/2024',
 '01/12/2023',
 '07/20/2022',
 '10/28/2022',
 '02/28/2020',
 '02/27/2020',
 '02/29/2020',
 '08/12/2021',
 '01/17/2023',
 '04/01/2024',
 '08/13/2021',
 '02/06/2024',
 '09/17/2022',
 '09/16/2021',
 '07/08/2020',
 '04/08/2024',
 '04/09/2020',
 '06/25/2021',
 '04/11/2024',
 '11/09/2022',
 '04/15/2024',
 '11/12/2021',
 '07/07/2021',
 '12/31/2020',
 '01/22/2023',
 '11/17/2021',
 '11/20/2022',
 '11/18/2020',
 '03/03/2022',
 '02/24/2020',
 '11/10/2023',
 '09/24/2022',
 '10/06/2023',
 '07/18/2008',
 '04/07/2014',
 '02/07/2024',
 '01/21/2015',
 '03/30/2015',
 '09/02/2020',
 '10/02/2014',
 '07/30/2021',
 '12/14/2021',
 '08/15/2023',
 '12/17/2021',
 '08/11/2023',
 '01/01/2022',
 '08/28/2020',
 '12/18/2020',
 '08/29/2020',
 '07/22/2020',
 '09/10/2021',
 '02/09/2020',
 '09/14/2021',
 '09/13/2021',
 '09/18/2021',
 '09/06/2023',
 '09/08/2023',
 '02/08/2024',
 '09/23/2021',
 '03/17/2022',
 '10/05/2021',
 '09/13/2023',
 '07/11/2020',
 '06/24/2020',
 '10/12/2021',
 '06/09/2021',
 '08/01/2020',
 '05/31/2023',
 '06/29/2023',
 '06/30/2023',
 '07/03/2023',
 '07/07/2023',
 '04/11/2021',
 '04/17/2020',
 '10/25/2021',
 '04/08/2022',
 '10/02/2020',
 '10/10/2020',
 '10/16/2020',
 '10/31/2020',
 '04/25/2023',
 '09/30/2019',
 '02/16/2022',
 '05/10/2021',
 '08/14/2021',
 '06/13/2020',
 '02/20/2024',
 '08/19/2022',
 '04/27/2023',
 '02/21/2024',
 '07/23/2018',
 '02/04/2023',
 '04/18/2022',
 '06/25/2020',
 '12/02/2021',
 '08/15/2019',
 '07/01/2021',
 '11/06/2021',
 '05/01/2023',
 '11/02/2023',
 '10/08/2022',
 '02/23/2024',
 '02/26/2024',
 '08/16/2020',
 '04/04/2020',
 '04/26/2021',
 '02/27/2021',
 '10/20/2022',
 '12/30/2021',
 '01/02/2021',
 '01/01/2021',
 '04/28/2020',
 '05/11/2020',
 '07/27/2021',
 '05/23/2020',
 '05/30/2020',
 '05/06/2023',
 '10/07/2020',
 '06/12/2020',
 '11/11/2021',
 '09/03/2020',
 '12/01/2020',
 '08/08/2022',
 '02/05/2022',
 '10/05/2018',
 '08/13/2022',
 '10/07/2019',
 '04/22/2022',
 '08/26/2022',
 '11/11/2023',
 '02/16/2023',
 '01/21/2023',
 '09/10/2022',
 '02/09/2022',
 '01/09/2023',
 '04/11/2020',
 '05/09/2023',
 '09/30/2021',
 '03/19/2022',
 '06/10/2008',
 '08/25/2008',
 '10/01/2008',
 '11/26/2008',
 '10/17/2020',
 '05/08/2024',
 '03/25/2023',
 '07/30/2022',
 '06/26/2013',
 '08/01/2014',
 '06/30/2015',
 '11/07/2020',
 '09/05/2019',
 '06/02/2023',
 '09/18/2020',
 '12/11/2021',
 '06/05/2023',
 '06/13/2023',
 '09/01/2020',
 '05/10/2024',
 '10/01/2020',
 '09/28/2022',
 '06/29/2021',
 '05/31/2021',
 '12/23/2021',
 '07/05/2023',
 '07/10/2023',
 '07/16/2021',
 '07/19/2021',
 '07/23/2020',
 '03/20/2022',
 '12/13/2020',
 '04/03/2022',
 '06/01/2020',
 '09/07/2018',
 '03/02/2024',
 '06/04/2019',
 '11/12/2019',
 '05/23/2022',
 '08/29/2023',
 '08/31/2023',
 '09/11/2023',
 '09/05/2023',
 '09/19/2023',
 '09/25/2023',
 '01/04/2021',
 '02/22/2020',
 '09/29/2023',
 '04/25/2020',
 '04/28/2021',
 '02/18/2024',
 '03/01/2021',
 '01/05/2021',
 '03/07/2020',
 '10/17/2023',
 '10/23/2020',
 '04/06/2024',
 '04/05/2024',
 '08/08/2021',
 '12/28/2021',
 '03/06/2024',
 '08/12/2023',
 '08/23/2020',
 '12/31/2018',
 '06/14/2019',
 '06/21/2019',
 '07/10/2019',
 '08/12/2019',
 '08/23/2019',
 '08/28/2019',
 '10/01/2019',
 '05/13/2023',
 '05/23/2023',
 '03/12/2024',
 '06/06/2023',
 '05/12/2021',
 '01/13/2023',
 '10/12/2020',
 '10/03/2017',
 '05/03/2022',
 '02/17/2023',
 '02/21/2023',
 '06/03/2009',
 '03/09/2010',
 '04/14/2010',
 '11/29/2011',
 '12/11/2012',
 '09/24/2015',
 '06/25/2022',
 '12/29/2021',
 '06/06/2022',
 '01/14/2022',
 '02/10/2022',
 '01/06/2021',
 '09/07/2021',
 '02/11/2022',
 '03/11/2020',
 '10/03/2021',
 '10/15/2021',
 '10/24/2020',
 '05/24/2023',
 '11/11/2020',
 '11/19/2020',
 '11/23/2020',
 '03/19/2024',
 '08/27/2022',
 '08/30/2022',
 ...]

In [4]:
## read in the developments data
developments = pd.read_csv('../input/coded_files/addresses_updated_120525.csv',dtype={'bbl':'object',
                                                                                    'house_num':'object',
                                                                                    'bbl':'object',
                                                                                    'bin':'object'})

In [5]:
developments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1531 entries, 0 to 1530
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   bbl          1508 non-null   object
 1   bldg         1431 non-null   float64
 2   m            1127 non-null   object
 3   og_address   1530 non-null   object
 4   zip code     1527 non-null   float64
 5   cd           1527 non-null   float64
 6   fc           1527 non-null   float64
 7   ss           1527 non-null   float64
 8   sa           1527 non-null   float64
 9   cc           1527 non-null   float64
 10  bin          1508 non-null   object
 11  dev_name     1531 non-null   object
 12  boro         1531 non-null   object
 13  units        1514 non-null   object
 14  transfer     1510 non-null   object
 15  new_address  1530 non-null   object
dtypes: float64(7), object(9)
memory usage: 191.5+ KB

## Cleaning

In [6]:
## rename address/boro columns so we can match later
developments = developments.rename(columns = {'new_address':'full_address',
                                              'borough':'boro'})

In [7]:
## make all columns in the OMO df all lowercase (for matching)
omo_df.columns = omo_df.columns.str.lower()

In [8]:
## stripping of whitespace
developments['bbl'] = developments['bbl'].str.strip()
developments['bin'] = developments['bin'].str.strip()
developments['full_address'] = developments['full_address'].str.strip()

In [9]:
## stripping of whitespace
omo_df['streetname'] = omo_df['streetname'].str.strip()
omo_df['housenumber'] = omo_df['housenumber'].str.strip()
omo_df['bbl'] = omo_df['bbl'].str.strip()
omo_df['bin'] = omo_df['bin'].str.strip()

In [10]:
## create a full street address in the OMO data by combining house number and street name
omo_df['full_address'] = omo_df['housenumber'] + ' ' + omo_df['streetname']

In [11]:
omo_df.boro.unique()

array(['Bronx', 'Queens', 'Brooklyn', 'Manhattan', 'Staten Island'],
      dtype=object)

In [12]:
developments.boro.unique()

array(['brooklyn', 'bronx', 'manhattan', 'queens', 'staten island'],
      dtype=object)

In [13]:
## create a dict of boroughs
omo_boro_changes = {'Bronx':'bronx',
                'Queens':'queens',
                'Manhattan':'manhattan',
                'Brooklyn':'brooklyn',
                'Staten Island':'staten island'}

In [14]:
## replace previous spellings with new spellings
omo_df['boro'] = omo_df['boro'].replace(omo_boro_changes)

## Merging

In [18]:
## combine on full address and borough, inner so we drop the developments with no data
combined_df = pd.merge(omo_df,
                       developments,
                       on = ['full_address','boro'],
                       how = 'left',
                       indicator=True)

In [19]:
## filter for only rows that are in both datasets
both_df = combined_df[combined_df['_merge']=='both'].reset_index()

In [20]:
both_df

,index,omoid,omonumber,buildingid,boro id,boro,housenumber,streetname,apartment,zip,...,cd,fc,ss,sa,cc,bin_y,dev_name,units,transfer,_merge
0,7,5371519,EO08654,809554,3,brooklyn,726,STANLEY AVENUE,NaN,11207,...,5.0,8.0,19.0,60.0,42.0,3324277,BOULEVARD,"1,441",12/28/2021,both
1,667,5298572,EN12278,809926,3,brooklyn,245,WORTMAN AVENUE,13D,11207,...,5.0,8.0,19.0,60.0,42.0,3324016,LINDEN,"1,586",12/28/2021,both
2,4243,5301673,EN13170,808855,3,brooklyn,320,MILLER AVENUE,NaN,11207,...,5.0,8.0,19.0,54.0,42.0,3327009,FIORENTINO PLAZA,160,12/28/2021,both
3,4277,5353121,EO02877,43031,1,manhattan,463,WEST 164 STREET,NaN,10032,...,12.0,13.0,31.0,72.0,10.0,1062641,WASHINGTON HEIGHTS REHAB PHASE III (FORT WASHI...,88,11/30/2020,both
4,4288,5353128,EO02882,43298,1,manhattan,509,WEST 176 STREET,NaN,10033,...,12.0,13.0,31.0,72.0,10.0,1063207,WASHINGTON HEIGHTS REHAB (GROUPS 1&2),216,11/30/2020,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,493373,5529876,EP28137,380678,3,brooklyn,104,TAPSCOTT STREET,NaN,11212,...,16.0,9.0,25.0,55.0,41.0,3081191,104-14 TAPSCOTT STREET,30,11/28/2023,both
409,493663,5530995,EP28738,363151,3,brooklyn,1142,LENOX ROAD,NaN,11212,...,17.0,9.0,19.0,58.0,41.0,3101906,LENOX ROAD-ROCKAWAY PARKWAY,74,11/28/2023,both
410,493665,5531326,EP28901,806340,2,bronx,400,BROOK AVENUE,NaN,10454,...,1.0,14.0,29.0,84.0,8.0,2090994,BETANCES I,309,11/16/2018,both
411,493976,5531846,EP29155,41707,1,manhattan,145,WEST 143 STREET,4B,10030,...,10.0,13.0,30.0,71.0,9.0,1060133,SAMUEL (CITY),664,9/26/2024,both
412,494049,5500108,EP13714,40685,1,manhattan,515,WEST 134 STREET,4D,10031,...,9.0,13.0,30.0,70.0,7.0,1059758,MANHATTANVILLE REHAB (GROUP 2),46,11/30/2020,both

In [137]:
## write to a csv
#both_df.to_csv('../output/omo_data_12022025.csv')

In [21]:
both_df.dev_name.value_counts().head(10)

dev_name
BOULEVARD                                   48
LINDEN                                      36
EDENWALD                                    33
OCEAN BAY APARTMENTS (BAYSIDE)              20
SAMUEL (CITY)                               18
STERLING PLACE REHABS (STERLING-BUFFALO)    17
PARK ROCK REHAB                             15
MANHATTANVILLE                              12
FIORENTINO PLAZA                            11
HARLEM RIVER                                11
Name: count, dtype: int64

In [22]:
both_df.dev_name.nunique()

60

In [23]:
both_df.omoid.nunique()

410

## Analyze

In [24]:
## change dtype for the dates in which the OMOs were created
both_df['omocreatedate'] = both_df['omocreatedate'].astype('datetime64[ns]')

In [25]:
omos_21_25 = both_df[(both_df['omocreatedate'] >= '01-01-2021') & (both_df['omocreatedate'] <= '09-25-2025')]

In [26]:
omos_21_25.shape

(372, 49)

In [27]:
omos_21_25.omoid.nunique()

369

In [31]:
omos_21_25.omoid.unique().tolist()

['5371519',
 '5298572',
 '5301673',
 '5353121',
 '5353128',
 '5383993',
 '5353460',
 '5330397',
 '5420954',
 '5352275',
 '5061671',
 '5113589',
 '5301230',
 '5434909',
 '5303615',
 '5442834',
 '5331751',
 '5409831',
 '5301671',
 '5355930',
 '5359144',
 '5410478',
 '5356224',
 '5358064',
 '5299528',
 '5304210',
 '5173849',
 '5201917',
 '5412950',
 '5413654',
 '5377488',
 '5275152',
 '5295471',
 '5413741',
 '5526002',
 '5303712',
 '5256370',
 '5289492',
 '5236638',
 '5288713',
 '5304208',
 '5316817',
 '5316429',
 '5316830',
 '5358008',
 '5327416',
 '5179863',
 '5318066',
 '5299198',
 '5360694',
 '5362248',
 '5268990',
 '5286755',
 '5386971',
 '5409768',
 '5364013',
 '5318732',
 '5286767',
 '5239597',
 '5306320',
 '5199351',
 '5237017',
 '5189708',
 '5286216',
 '5336342',
 '5337391',
 '5200170',
 '5413390',
 '5271773',
 '5275490',
 '5149971',
 '5368035',
 '5260330',
 '5200168',
 '5540285',
 '5340228',
 '5200293',
 '5318701',
 '5235048',
 '5277791',
 '5221630',
 '5430910',
 '5242250',
 '5195709',
 '5322129',
 '5183930',
 '5289348',
 '5245671',
 '5418696',
 '5298850',
 '5292546',
 '5315433',
 '5247432',
 '5148490',
 '5367192',
 '5394108',
 '5365674',
 '5236263',
 '5205731',
 '5325308',
 '5255594',
 '5423069',
 '5354369',
 '5237437',
 '5342830',
 '5275002',
 '5279958',
 '5373363',
 '5293528',
 '5321350',
 '5280330',
 '5343491',
 '5344704',
 '5342687',
 '5342553',
 '5246888',
 '5371560',
 '5322549',
 '5323812',
 '5425756',
 '5426468',
 '5343452',
 '5265508',
 '5343429',
 '5374919',
 '5366812',
 '5310191',
 '5297726',
 '5322552',
 '5374923',
 '5346793',
 '5292424',
 '5430150',
 '5294135',
 '5374872',
 '5237428',
 '5324677',
 '5357465',
 '5326897',
 '5374952',
 '5374891',
 '5348459',
 '5428740',
 '5281718',
 '5326598',
 '5375732',
 '5430188',
 '5400024',
 '5333365',
 '5347208',
 '5398088',
 '5292774',
 '5295130',
 '5347762',
 '5440557',
 '5348337',
 '5348341',
 '5295720',
 '5351454',
 '5326898',
 '5351504',
 '5428359',
 '5352274',
 '5403535',
 '5403231',
 '5403248',
 '5436054',
 '5331336',
 '5284434',
 '5408829',
 '5436414',
 '5450988',
 '5435716',
 '5451534',
 '5271996',
 '5327475',
 '5434553',
 '5406602',
 '5438221',
 '5452419',
 '5452411',
 '5328009',
 '5436197',
 '5326216',
 '5330183',
 '5451932',
 '5330184',
 '5453117',
 '5331112',
 '5454810',
 '5454960',
 '5456135',
 '5457557',
 '5450051',
 '5478271',
 '5476356',
 '5476210',
 '5497625',
 '5497745',
 '5497610',
 '5457550',
 '5450771',
 '5476351',
 '5478229',
 '5480675',
 '5430011',
 '5446915',
 '5480368',
 '5481800',
 '5461156',
 '5450378',
 '5499728',
 '5481091',
 '5371515',
 '5438691',
 '5499785',
 '5501917',
 '5481513',
 '5499725',
 '5479580',
 '5411068',
 '5412798',
 '5462705',
 '5413689',
 '5504505',
 '5482450',
 '5427952',
 '5504126',
 '5462264',
 '5496606',
 '5453119',
 '5408712',
 '5461688',
 '5463511',
 '5464454',
 '5462268',
 '5399657',
 '5462387',
 '5533205',
 '5533245',
 '5486927',
 '5486181',
 '5495754',
 '5468172',
 '5488461',
 '5488462',
 '5466348',
 '5442430',
 '5442453',
 '5464948',
 '5466608',
 '5469099',
 '5489931',
 '5428364',
 '5469242',
 '5469243',
 '5462307',
 '5492392',
 '5279624',
 '5346310',
 '5495448',
 '5541598',
 '5542043',
 '5541001',
 '5541877',
 '5540336',
 '5540117',
 '5460441',
 '5509138',
 '5509137',
 '5509334',
 '5535043',
 '5535541',
 '5504971',
 '5535218',
 '5535282',
 '5497297',
 '5503428',
 '5507314',
 '5525716',
 '5534834',
 '5510005',
 '5530445',
 '5537228',
 '5480632',
 '5505950',
 '5511156',
 '5535835',
 '5535839',
 '5536074',
 '5536135',
 '5537230',
 '5463216',
 '5544241',
 '5511178',
 '5538516',
 '5512261',
 '5512388',
 '5544246',
 '5481498',
 '5540157',
 '5513035',
 '5512688',
 '5513367',
 '5537235',
 '5539222',
 '5539214',
 '5539066',
 '5538184',
 '5540536',
 '5545984',
 '5512204',
 '5514751',
 '5524462',
 '5537274',
 '5524474',
 '5529369',
 '5498085',
 '5539218',
 '5528009',
 '5538186',
 '5539867',
 '5515221',
 '5482451',
 '5514906',
 '5514905',
 '5546715',
 '5506567',
 '5540734',
 '5514679',
 '5540384',
 '5514925',
 '5531024',
 '5487686',
 '5547614',
 '5516028',
 '5517494',
 '5517149',
 '5497976',
 '5518820',
 '5519665',
 '5519558',
 '5496605',
 '5519959',
 '5521387',
 '5529705',
 '5521945',
 '5521190',
 '5525235',
 '5526719',
 '5527852',
 '5528147',
 '5527753',
 '5528258',
 '5528659',
 '5528588',
 '5529230',
 '5528811',
 '5528826',
 '5522118',
 '5529967',
 '5529035',
 '5530529',
 '5530915',
 '5529876',
 '5530995',
 '5531326',
 '5531846',
 '5500108']

In [28]:
omos_21_25.to_csv('../output/testing_omos_12825.csv')

In [29]:
omos_21_25.dev_name.nunique()

59

In [30]:
omos_21_25.omocreatedate.dt.year.value_counts().reset_index()

   omocreatedate  count
0           2024    118
1           2025     99
2           2023     85
3           2022     54
4           2021     16

## Detour: Looking at Boulevard

In [44]:
boulevard_df = both_df[both_df['dev_name'] == 'BOULEVARD']

In [45]:
boulevard_df.omocreatedate.dt.year.value_counts().reset_index()

   omocreatedate  count
0           2023     19
1           2024     16
2           2025      7
3           2022      6

In [33]:
annual_grouped.to_csv('../output/omo_annual.csv')

In [36]:
median_cost = combined_df.groupby('development')['omoawardamount'].median().reset_index(name = 'median_omo_cost')

TypeError: agg function failed [how->median,dtype->object]

In [ ]:
median_cost.sort_values(by = 'median_omo_cost',ascending = False).head(10)

In [ ]:
total_cost = combined_df.groupby('development_name')['omoawardamount'].sum().reset_index(name = 'total_cost')

In [ ]:
count_w_money = pd.merge(development_count,median_cost,on='development_name',how='left')

In [ ]:
count_w_money.sort_values(by = 'median_omo_cost', ascending = False)

In [ ]:
count_w_money.sort_values(by = 'median_omo_cost', ascending = False)

In [ ]:
combined_df.to_csv('../output/omo_developments_merged.csv')